const pool = require('./pool');

async function recreateDemoPatient(client, data, userId) {
  let step = 'paciente';

  try {
    await client.query('DELETE FROM pacientes WHERE no_expediente = $1', [data.paciente.no_expediente]);

  const patientPayload = {
    ...data.paciente,
    registrado_por: userId,
  };
  const patientColumns = Object.keys(patientPayload);
  const patientValues = Object.values(patientPayload);
  const patientPlaceholders = patientColumns.map((_, index) => `$${index + 1}`).join(', ');

  const pacienteInsert = await client.query(
    `INSERT INTO pacientes (${patientColumns.join(', ')})
     VALUES (${patientPlaceholders})
     RETURNING id`,
    patientValues
  );
  const pacienteId = pacienteInsert.rows[0].id;
  step = 'embarazo';

  const embarazoInsert = await client.query(
    `INSERT INTO embarazos (
      paciente_id, numero_embarazo, estado, fur, fpp, fecha_inicio, fecha_cierre,
      observaciones, registrado_por
    ) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
    RETURNING id`,
    [
      pacienteId,
      data.embarazo.numero_embarazo,
      data.embarazo.estado,
      data.embarazo.fur,
      data.embarazo.fpp,
      data.embarazo.fecha_inicio,
      data.embarazo.fecha_cierre,
      data.embarazo.observaciones,
      userId,
    ]
  );
  const embarazoId = embarazoInsert.rows[0].id;
  step = 'vacunas';

  for (const vacuna of data.vacunas) {
    await client.query(
      `INSERT INTO vacunas_paciente (
        paciente_id, embarazo_id, tipo_vacuna, momento, numero_dosis, fecha_dosis, registrado_por
      ) VALUES ($1,$2,$3,$4,$5,$6,$7)`,
      [pacienteId, embarazoId, vacuna.tipo_vacuna, vacuna.momento, vacuna.numero_dosis, vacuna.fecha_dosis, userId]
    );
  }

  for (const control of data.controles) {
    step = `control_${control.numero_control}`;
    await client.query(
      `INSERT INTO controles_prenatales (
        paciente_id, embarazo_id, numero_control, fecha, hora, motivo_consulta,
        peligro_hemorragia_vaginal, peligro_palidez, peligro_dolor_cabeza, peligro_hipertension,
        peligro_dolor_epigastrico, peligro_trastornos_visuales, peligro_fiebre, peligro_otro,
        edad_gestacional_semanas, nombre_acompanante, nombre_cargo_atiende,
        pa_sistolica, pa_diastolica, frecuencia_cardiaca, frecuencia_respiratoria,
        temperatura, perimetro_braquial_cm, peso_kg, talla_cm, imc, examen_bucodental, examen_mamas,
        altura_uterina_cm, fcf, movimientos_fetales, situacion_fetal, presentacion_fetal,
        sangre_manchado, verrugas_herpes_papilomas, flujo_vaginal, otros_ginecologico,
        hematologia_realizada, hematologia_resultado, glicemia_realizada, glicemia_resultado,
        grupo_rh_realizado, grupo_rh_resultado, orina_realizada, orina_bacteriuria, orina_proteinuria,
        heces_realizada, heces_resultado, vih_realizado, vih_resultado, vih_resultado_valor,
        vdrl_realizado, vdrl_resultado, vdrl_tratamiento_indicado,
        torch_realizado, torch_resultado_positivo, torch_resultado_valor,
        papanicolau_ivaa_realizado, papanicolau_ivaa_fecha_toma, papanicolau_ivaa_resultado,
        hepatitis_b_realizado, hepatitis_b_resultado, otros_lab,
        usg_realizado, usg_hallazgos, sulfato_ferroso, sulfato_ferroso_tabletas,
        acido_folico, acido_folico_tabletas, suplementacion_hallazgos, suplementacion_tratamiento,
        orient_plan_emergencia_parto, orient_alimentacion_embarazo, orient_senales_peligro,
        orient_lactancia_materna, orient_planificacion_familiar, orient_importancia_postparto,
        orient_vacunacion_nino, orient_pre_post_prueba_vih, orient_importancia_atenciones,
        orient_tratamiento_its_pareja, orient_otros, impresion_clinica, tratamiento, cita_siguiente,
        registrado_por
      ) VALUES (
        $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,
        $11,$12,$13,$14,$15,$16,$17,$18,$19,$20,
        $21,$22,$23,$24,$25,$26,$27,$28,$29,$30,
        $31,$32,$33,$34,$35,$36,$37,$38,$39,$40,
        $41,$42,$43,$44,$45,$46,$47,$48,$49,$50,
        $51,$52,$53,$54,$55,$56,$57,$58,$59,$60,
        $61,$62,$63,$64,$65,$66,$67,$68,$69,$70,
        $71,$72,$73,$74,$75,$76,$77,$78,$79,$80,
        $81,$82,$83,$84,$85,$86
      )`,
      [
        pacienteId, embarazoId, control.numero_control, control.fecha, control.hora, control.motivo_consulta,
        control.peligro_hemorragia_vaginal, control.peligro_palidez, control.peligro_dolor_cabeza, control.peligro_hipertension,
        control.peligro_dolor_epigastrico, control.peligro_trastornos_visuales, control.peligro_fiebre, control.peligro_otro,
        control.edad_gestacional_semanas, control.nombre_acompanante, control.nombre_cargo_atiende,
        control.pa_sistolica, control.pa_diastolica, control.frecuencia_cardiaca, control.frecuencia_respiratoria,
        control.temperatura, control.perimetro_braquial_cm, control.peso_kg, control.talla_cm, control.imc, control.examen_bucodental, control.examen_mamas,
        control.altura_uterina_cm, control.fcf, control.movimientos_fetales, control.situacion_fetal, control.presentacion_fetal,
        control.sangre_manchado, control.verrugas_herpes_papilomas, control.flujo_vaginal, control.otros_ginecologico,
        control.hematologia_realizada, control.hematologia_resultado, control.glicemia_realizada, control.glicemia_resultado,
        control.grupo_rh_realizado, control.grupo_rh_resultado, control.orina_realizada, control.orina_bacteriuria, control.orina_proteinuria,
        control.heces_realizada, control.heces_resultado, control.vih_realizado, control.vih_resultado, control.vih_resultado_valor,
        control.vdrl_realizado, control.vdrl_resultado, control.vdrl_tratamiento_indicado,
        control.torch_realizado, control.torch_resultado_positivo, control.torch_resultado_valor,
        control.papanicolau_ivaa_realizado, control.papanicolau_ivaa_fecha_toma, control.papanicolau_ivaa_resultado,
        control.hepatitis_b_realizado, control.hepatitis_b_resultado, control.otros_lab,
        control.usg_realizado, control.usg_hallazgos, control.sulfato_ferroso, control.sulfato_ferroso_tabletas,
        control.acido_folico, control.acido_folico_tabletas, control.suplementacion_hallazgos, control.suplementacion_tratamiento,
        control.orient_plan_emergencia_parto, control.orient_alimentacion_embarazo, control.orient_senales_peligro,
        control.orient_lactancia_materna, control.orient_planificacion_familiar, control.orient_importancia_postparto,
        control.orient_vacunacion_nino, control.orient_pre_post_prueba_vih, control.orient_importancia_atenciones,
        control.orient_tratamiento_its_pareja, control.orient_otros, control.impresion_clinica, control.tratamiento, control.cita_siguiente,
        userId,
      ]
    );
  }

  for (const morbilidad of data.morbilidad) {
    step = `morbilidad_${morbilidad.fecha}`;
    await client.query(
      `INSERT INTO morbilidad_embarazo (
        paciente_id, embarazo_id, fecha, hora, motivo_consulta, historia_enfermedad_actual,
        revision_por_sistemas, examen_fisico, impresion_clinica, tratamiento_referencia,
        nombre_cargo_atiende, registrado_por
      ) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12)`,
      [
        pacienteId,
        embarazoId,
        morbilidad.fecha,
        morbilidad.hora,
        morbilidad.motivo_consulta,
        morbilidad.historia_enfermedad_actual,
        morbilidad.revision_por_sistemas,
        morbilidad.examen_fisico,
        morbilidad.impresion_clinica,
        morbilidad.tratamiento_referencia,
        morbilidad.nombre_cargo_atiende,
        userId,
      ]
    );
  }

  for (const puerperio of data.puerperio) {
    step = `puerperio_${puerperio.numero_atencion}`;
    await client.query(
      `INSERT INTO controles_puerperio (
        paciente_id, embarazo_id, numero_atencion, fecha, hora, signos_peligro,
        dias_despues_parto, lugar_atencion_parto, quien_atendio_parto, recien_nacido_vivo,
        tipo_parto, tuvo_apego_inmediato, lactancia_materna_exclusiva, herida_operatoria,
        pa_sistolica, pa_diastolica, frecuencia_cardiaca, frecuencia_respiratoria, temperatura,
        examen_mamas, examen_ginecologico, orientacion_consejeria, impresion_clinica,
        tratamiento, nombre_cargo_atiende, registrado_por
      ) VALUES (
        $1,$2,$3,$4,$5,$6,$7,$8,$9,$10,
        $11,$12,$13,$14,$15,$16,$17,$18,$19,$20,
        $21,$22,$23,$24,$25,$26
      )`,
      [
        pacienteId,
        embarazoId,
        puerperio.numero_atencion,
        puerperio.fecha,
        puerperio.hora,
        puerperio.signos_peligro,
        puerperio.dias_despues_parto,
        puerperio.lugar_atencion_parto,
        puerperio.quien_atendio_parto,
        puerperio.recien_nacido_vivo,
        puerperio.tipo_parto,
        puerperio.tuvo_apego_inmediato,
        puerperio.lactancia_materna_exclusiva,
        puerperio.herida_operatoria,
        puerperio.pa_sistolica,
        puerperio.pa_diastolica,
        puerperio.frecuencia_cardiaca,
        puerperio.frecuencia_respiratoria,
        puerperio.temperatura,
        puerperio.examen_mamas,
        puerperio.examen_ginecologico,
        puerperio.orientacion_consejeria,
        puerperio.impresion_clinica,
        puerperio.tratamiento,
        puerperio.nombre_cargo_atiende,
        userId,
      ]
    );
  }

  step = 'plan_parto';
  const planPayload = {
    paciente_id: pacienteId,
    embarazo_id: embarazoId,
    ...data.planParto,
    registrado_por: userId,
  };
  const planColumns = Object.keys(planPayload);
  const planValues = Object.values(planPayload);
  const planPlaceholders = planColumns.map((_, index) => `$${index + 1}`).join(', ');
  await client.query(
    `INSERT INTO planes_parto (${planColumns.join(', ')})
     VALUES (${planPlaceholders})`,
    planValues
  );

  step = 'ficha_riesgo';
  const riskPayload = {
    paciente_id: pacienteId,
    embarazo_id: embarazoId,
    ...data.riesgo,
    registrado_por: userId,
  };
  const riskColumns = Object.keys(riskPayload);
  const riskValues = Object.values(riskPayload);
  const riskPlaceholders = riskColumns.map((_, index) => `$${index + 1}`).join(', ');
  await client.query(
    `INSERT INTO fichas_riesgo_obstetrico (${riskColumns.join(', ')})
     VALUES (${riskPlaceholders})`,
    riskValues
  );

  for (const referencia of data.referencias) {
    step = `referencia_${referencia.fecha}`;
    await client.query(
      `INSERT INTO referencias_efectuadas (
        paciente_id, fecha, lugar_referencia, diagnostico, registrado_por
      ) VALUES ($1,$2,$3,$4,$5)`,
      [pacienteId, referencia.fecha, referencia.lugar_referencia, referencia.diagnostico, userId]
    );
  }

    return { pacienteId, embarazoId };
  } catch (error) {
    error.message = `${error.message} [paso: ${step}]`;
    throw error;
  }
}

const demoPatients = [
  {
    paciente: {
      no_expediente: 'DEMO-EMB-001',
      cui: '3012456780101',
      nombre_establecimiento: 'CAP El Chal',
      distrito: 'Distrito Sur Oriente',
      area_salud: 'Peten, Area Sur Oriente',
      categoria_servicio: 'CAP',
      nombres: 'Mariela Fernanda',
      apellidos: 'Cocom Ical',
      fecha_nacimiento: '1998-08-14',
      rango_edad: '20_35',
      clasificacion_alfa_beta: 'ALFA',
      domicilio: 'Barrio El Centro, lote 12',
      municipio: 'El Chal',
      territorio: 'Territorio 1',
      sector: 'Sector A',
      comunidad: 'El Chal Centro',
      telefono: '55112233',
      cobertura_igss: false,
      cobertura_privada: true,
      cobertura_privada_detalle: 'Seguro cooperativa local',
      viene_referida: true,
      referida_de: 'Puesto de Salud Santa Amelia',
      nivel_estudios: 'diversificado',
      ultimo_anio_aprobado: 5,
      profesion_oficio: 'Comerciante',
      estado_civil: 'unida',
      vive_sola: false,
      nombre_esposo_conviviente: 'Luis Alberto Tun',
      es_migrante: false,
      migrante_municipio_depto_pais: null,
      pueblo: 'maya',
      comunidad_linguistica: 'Qeqchi',
      fuma_activamente: false,
      fuma_pasivamente: false,
      consume_drogas: false,
      consume_alcohol: false,
      fuma_activamente_1er_trimestre: false,
      fuma_activamente_2do_trimestre: false,
      fuma_activamente_3er_trimestre: false,
      fuma_pasivamente_1er_trimestre: false,
      fuma_pasivamente_2do_trimestre: false,
      fuma_pasivamente_3er_trimestre: false,
      consume_alcohol_1er_trimestre: false,
      consume_alcohol_2do_trimestre: false,
      consume_alcohol_3er_trimestre: false,
      consume_drogas_1er_trimestre: false,
      consume_drogas_2do_trimestre: false,
      consume_drogas_3er_trimestre: false,
      violencia_1er_trimestre: false,
      violencia_2do_trimestre: false,
      violencia_3er_trimestre: false,
      embarazo_abuso_sexual: false,
      fur: '2026-01-18',
      fpp: '2026-10-25',
      eg_confiable_fur: true,
      eg_confiable_usg: true,
      gestas_previas: 2,
      abortos: 1,
      partos_vaginales: 1,
      cesareas: 0,
      nacidos_vivos: 1,
      nacidos_muertos: 0,
      hijos_viven: 1,
      muertos_antes_1sem: 0,
      muertos_despues_1sem: 0,
      cirugia_genito_urinaria: false,
      infertilidad: false,
      fin_embarazo_anterior: '2022-06-03',
      fin_embarazo_menos_1anio: false,
      embarazo_planeado: true,
      fracaso_metodo: 'no',
      antec_diabetes: false,
      antec_diabetes_tipo: null,
      antec_tbc: false,
      antec_hipertension: false,
      antec_preeclampsia: false,
      antec_eclampsia: false,
      antec_cardiopatia: false,
      antec_nefropatia: false,
      antec_otra_condicion: false,
      antec_otra_condicion_desc: null,
      cirugia_genito_urinaria_pers: false,
      fam_diabetes: true,
      fam_tbc: false,
      fam_hipertension: true,
      fam_preeclampsia: false,
      fam_eclampsia: false,
      fam_cardiopatia: false,
      fam_gemelos: false,
      fam_otra_condicion_medica_grave: false,
      rn_nc: false,
      rn_normal: true,
      rn_menor_2500g: false,
      rn_mayor_4000g: false,
      antec_vih_positivo: false,
      antec_emb_ectopico_num: 0,
      antec_emb_ectopico: false,
      antec_gemelares: false,
      abortos_3_espont_consecutivos: false,
      antec_violencia: false,
      tiene_ficha_riesgo: true,
    },
    embarazo: {
      numero_embarazo: 3,
      estado: 'activo',
      fur: '2026-01-18',
      fpp: '2026-10-25',
      fecha_inicio: '2026-01-18',
      fecha_cierre: null,
      observaciones: 'Paciente demo con expediente completo para pruebas funcionales.',
    },
    vacunas: [
      { tipo_vacuna: 'td_tdap', momento: 'durante_embarazo', numero_dosis: 1, fecha_dosis: '2026-05-03' },
      { tipo_vacuna: 'influenza', momento: 'durante_embarazo', numero_dosis: 1, fecha_dosis: '2026-05-03' },
      { tipo_vacuna: 'spr_sr', momento: 'previo_embarazo', numero_dosis: 1, fecha_dosis: '2025-11-20' },
    ],
    controles: [
      {
        numero_control: 1,
        fecha: '2026-05-03',
        hora: '08:30',
        motivo_consulta: 'Primer control prenatal y apertura de expediente.',
        peligro_hemorragia_vaginal: false,
        peligro_palidez: false,
        peligro_dolor_cabeza: false,
        peligro_hipertension: false,
        peligro_dolor_epigastrico: false,
        peligro_trastornos_visuales: false,
        peligro_fiebre: false,
        peligro_otro: '',
        edad_gestacional_semanas: 15,
        nombre_acompanante: 'Luis Alberto Tun',
        nombre_cargo_atiende: 'Lic. Ana López',
        pa_sistolica: 110,
        pa_diastolica: 70,
        frecuencia_cardiaca: 78,
        frecuencia_respiratoria: 18,
        temperatura: 36.6,
        perimetro_braquial_cm: 28.5,
        peso_kg: 61.2,
        talla_cm: 158.0,
        imc: 24.52,
        examen_bucodental: true,
        examen_mamas: true,
        altura_uterina_cm: 15.0,
        fcf: 148,
        movimientos_fetales: true,
        situacion_fetal: 'Longitudinal',
        presentacion_fetal: 'No aplica',
        sangre_manchado: false,
        verrugas_herpes_papilomas: false,
        flujo_vaginal: false,
        otros_ginecologico: 'Sin hallazgos patológicos.',
        hematologia_realizada: true,
        hematologia_resultado: 'Hb 12.1 g/dL',
        glicemia_realizada: true,
        glicemia_resultado: '86 mg/dL',
        grupo_rh_realizado: true,
        grupo_rh_resultado: 'O+',
        orina_realizada: true,
        orina_bacteriuria: false,
        orina_proteinuria: false,
        heces_realizada: true,
        heces_resultado: 'Negativo',
        vih_realizado: true,
        vih_resultado: 'negativo',
        vih_resultado_valor: 'No reactivo',
        vdrl_realizado: true,
        vdrl_resultado: 'negativo',
        vdrl_tratamiento_indicado: false,
        torch_realizado: true,
        torch_resultado_positivo: false,
        torch_resultado_valor: 'Negativo',
        papanicolau_ivaa_realizado: true,
        papanicolau_ivaa_fecha_toma: '2026-05-03',
        papanicolau_ivaa_resultado: 'Normal',
        hepatitis_b_realizado: true,
        hepatitis_b_resultado: 'Negativo',
        otros_lab: 'TSH normal.',
        usg_realizado: true,
        usg_hallazgos: 'Gestación única intrauterina acorde a EG.',
        sulfato_ferroso: true,
        sulfato_ferroso_tabletas: 30,
        acido_folico: true,
        acido_folico_tabletas: 30,
        suplementacion_hallazgos: 'Buena adherencia.',
        suplementacion_tratamiento: 'Continuar suplementos diarios.',
        orient_plan_emergencia_parto: true,
        orient_alimentacion_embarazo: true,
        orient_senales_peligro: true,
        orient_lactancia_materna: true,
        orient_planificacion_familiar: true,
        orient_importancia_postparto: true,
        orient_vacunacion_nino: true,
        orient_pre_post_prueba_vih: true,
        orient_importancia_atenciones: true,
        orient_tratamiento_its_pareja: false,
        orient_otros: 'Hidratación y reposo.',
        impresion_clinica: 'Embarazo de 15 semanas sin complicaciones.',
        tratamiento: 'Complejo prenatal y seguimiento habitual.',
        cita_siguiente: '2026-05-24',
      },
      {
        numero_control: 2,
        fecha: '2026-05-24',
        hora: '09:10',
        motivo_consulta: 'Seguimiento control 2.',
        peligro_hemorragia_vaginal: false,
        peligro_palidez: false,
        peligro_dolor_cabeza: false,
        peligro_hipertension: false,
        peligro_dolor_epigastrico: false,
        peligro_trastornos_visuales: false,
        peligro_fiebre: false,
        peligro_otro: '',
        edad_gestacional_semanas: 18,
        nombre_acompanante: 'Madre',
        nombre_cargo_atiende: 'Lic. Ana López',
        pa_sistolica: 108,
        pa_diastolica: 68,
        frecuencia_cardiaca: 80,
        frecuencia_respiratoria: 18,
        temperatura: 36.7,
        perimetro_braquial_cm: 28.7,
        peso_kg: 62.0,
        talla_cm: 158.0,
        imc: 24.84,
        examen_bucodental: true,
        examen_mamas: true,
        altura_uterina_cm: 18.0,
        fcf: 150,
        movimientos_fetales: true,
        situacion_fetal: 'Longitudinal',
        presentacion_fetal: 'Cefálica',
        sangre_manchado: false,
        verrugas_herpes_papilomas: false,
        flujo_vaginal: false,
        otros_ginecologico: 'Sin alteraciones.',
        hematologia_realizada: false,
        hematologia_resultado: '',
        glicemia_realizada: false,
        glicemia_resultado: '',
        grupo_rh_realizado: false,
        grupo_rh_resultado: '',
        orina_realizada: true,
        orina_bacteriuria: false,
        orina_proteinuria: false,
        heces_realizada: false,
        heces_resultado: '',
        vih_realizado: false,
        vih_resultado: '',
        vih_resultado_valor: '',
        vdrl_realizado: false,
        vdrl_resultado: '',
        vdrl_tratamiento_indicado: false,
        torch_realizado: false,
        torch_resultado_positivo: false,
        torch_resultado_valor: '',
        papanicolau_ivaa_realizado: false,
        papanicolau_ivaa_fecha_toma: null,
        papanicolau_ivaa_resultado: '',
        hepatitis_b_realizado: false,
        hepatitis_b_resultado: '',
        otros_lab: '',
        usg_realizado: false,
        usg_hallazgos: '',
        sulfato_ferroso: true,
        sulfato_ferroso_tabletas: 30,
        acido_folico: true,
        acido_folico_tabletas: 30,
        suplementacion_hallazgos: 'Continúa bien.',
        suplementacion_tratamiento: 'Continuar.',
        orient_plan_emergencia_parto: true,
        orient_alimentacion_embarazo: true,
        orient_senales_peligro: true,
        orient_lactancia_materna: false,
        orient_planificacion_familiar: false,
        orient_importancia_postparto: false,
        orient_vacunacion_nino: false,
        orient_pre_post_prueba_vih: false,
        orient_importancia_atenciones: true,
        orient_tratamiento_its_pareja: false,
        orient_otros: 'Actividad física ligera.',
        impresion_clinica: 'Evolución normal.',
        tratamiento: 'Seguimiento prenatal.',
        cita_siguiente: '2026-06-21',
      },
      {
        numero_control: 3,
        fecha: '2026-06-21',
        hora: '08:45',
        motivo_consulta: 'Control prenatal del segundo trimestre.',
        peligro_hemorragia_vaginal: false,
        peligro_palidez: false,
        peligro_dolor_cabeza: false,
        peligro_hipertension: false,
        peligro_dolor_epigastrico: false,
        peligro_trastornos_visuales: false,
        peligro_fiebre: false,
        peligro_otro: '',
        edad_gestacional_semanas: 22,
        nombre_acompanante: 'Esposo',
        nombre_cargo_atiende: 'Dra. Carla Medina',
        pa_sistolica: 112,
        pa_diastolica: 72,
        frecuencia_cardiaca: 82,
        frecuencia_respiratoria: 18,
        temperatura: 36.5,
        perimetro_braquial_cm: 29.0,
        peso_kg: 63.1,
        talla_cm: 158.0,
        imc: 25.28,
        examen_bucodental: true,
        examen_mamas: true,
        altura_uterina_cm: 22.0,
        fcf: 146,
        movimientos_fetales: true,
        situacion_fetal: 'Longitudinal',
        presentacion_fetal: 'Cefálica',
        sangre_manchado: false,
        verrugas_herpes_papilomas: false,
        flujo_vaginal: false,
        otros_ginecologico: '',
        hematologia_realizada: true,
        hematologia_resultado: 'Hb 11.8 g/dL',
        glicemia_realizada: true,
        glicemia_resultado: '89 mg/dL',
        grupo_rh_realizado: false,
        grupo_rh_resultado: '',
        orina_realizada: true,
        orina_bacteriuria: false,
        orina_proteinuria: false,
        heces_realizada: false,
        heces_resultado: '',
        vih_realizado: false,
        vih_resultado: '',
        vih_resultado_valor: '',
        vdrl_realizado: false,
        vdrl_resultado: '',
        vdrl_tratamiento_indicado: false,
        torch_realizado: false,
        torch_resultado_positivo: false,
        torch_resultado_valor: '',
        papanicolau_ivaa_realizado: false,
        papanicolau_ivaa_fecha_toma: null,
        papanicolau_ivaa_resultado: '',
        hepatitis_b_realizado: false,
        hepatitis_b_resultado: '',
        otros_lab: 'Sin novedades.',
        usg_realizado: true,
        usg_hallazgos: 'Placenta posterior, crecimiento adecuado.',
        sulfato_ferroso: true,
        sulfato_ferroso_tabletas: 30,
        acido_folico: true,
        acido_folico_tabletas: 30,
        suplementacion_hallazgos: 'Tolera bien.',
        suplementacion_tratamiento: 'Continuar.',
        orient_plan_emergencia_parto: true,
        orient_alimentacion_embarazo: true,
        orient_senales_peligro: true,
        orient_lactancia_materna: true,
        orient_planificacion_familiar: true,
        orient_importancia_postparto: true,
        orient_vacunacion_nino: true,
        orient_pre_post_prueba_vih: false,
        orient_importancia_atenciones: true,
        orient_tratamiento_its_pareja: false,
        orient_otros: 'Mantener controles.',
        impresion_clinica: 'Gestación normal segundo trimestre.',
        tratamiento: 'Continuar plan prenatal.',
        cita_siguiente: '2026-07-19',
      },
      {
        numero_control: 4,
        fecha: '2026-07-19',
        hora: '09:00',
        motivo_consulta: 'Seguimiento tercer trimestre temprano.',
        peligro_hemorragia_vaginal: false,
        peligro_palidez: false,
        peligro_dolor_cabeza: false,
        peligro_hipertension: false,
        peligro_dolor_epigastrico: false,
        peligro_trastornos_visuales: false,
        peligro_fiebre: false,
        peligro_otro: '',
        edad_gestacional_semanas: 26,
        nombre_acompanante: 'Esposo',
        nombre_cargo_atiende: 'Dra. Carla Medina',
        pa_sistolica: 114,
        pa_diastolica: 72,
        frecuencia_cardiaca: 84,
        frecuencia_respiratoria: 18,
        temperatura: 36.7,
        perimetro_braquial_cm: 29.2,
        peso_kg: 64.0,
        talla_cm: 158.0,
        imc: 25.64,
        examen_bucodental: true,
        examen_mamas: true,
        altura_uterina_cm: 26.0,
        fcf: 144,
        movimientos_fetales: true,
        situacion_fetal: 'Longitudinal',
        presentacion_fetal: 'Cefálica',
        sangre_manchado: false,
        verrugas_herpes_papilomas: false,
        flujo_vaginal: false,
        otros_ginecologico: '',
        hematologia_realizada: false,
        hematologia_resultado: '',
        glicemia_realizada: false,
        glicemia_resultado: '',
        grupo_rh_realizado: false,
        grupo_rh_resultado: '',
        orina_realizada: true,
        orina_bacteriuria: false,
        orina_proteinuria: false,
        heces_realizada: false,
        heces_resultado: '',
        vih_realizado: false,
        vih_resultado: '',
        vih_resultado_valor: '',
        vdrl_realizado: false,
        vdrl_resultado: '',
        vdrl_tratamiento_indicado: false,
        torch_realizado: false,
        torch_resultado_positivo: false,
        torch_resultado_valor: '',
        papanicolau_ivaa_realizado: false,
        papanicolau_ivaa_fecha_toma: null,
        papanicolau_ivaa_resultado: '',
        hepatitis_b_realizado: false,
        hepatitis_b_resultado: '',
        otros_lab: '',
        usg_realizado: false,
        usg_hallazgos: '',
        sulfato_ferroso: true,
        sulfato_ferroso_tabletas: 30,
        acido_folico: true,
        acido_folico_tabletas: 30,
        suplementacion_hallazgos: 'Sin intolerancia.',
        suplementacion_tratamiento: 'Continuar.',
        orient_plan_emergencia_parto: true,
        orient_alimentacion_embarazo: true,
        orient_senales_peligro: true,
        orient_lactancia_materna: true,
        orient_planificacion_familiar: true,
        orient_importancia_postparto: true,
        orient_vacunacion_nino: true,
        orient_pre_post_prueba_vih: false,
        orient_importancia_atenciones: true,
        orient_tratamiento_its_pareja: false,
        orient_otros: 'Preparación de plan de parto.',
        impresion_clinica: 'Gestación evolutiva sin datos de alarma.',
        tratamiento: 'Seguimiento según norma.',
        cita_siguiente: '2026-08-16',
      },
    ],
    morbilidad: [
      {
        fecha: '2026-05-30',
        hora: '11:20',
        motivo_consulta: 'Infección urinaria leve',
        historia_enfermedad_actual: 'Disuria de 2 días de evolución.',
        revision_por_sistemas: 'Sin fiebre, sin sangrado.',
        examen_fisico: 'Paciente hidratada, abdomen blando.',
        impresion_clinica: 'ITU no complicada.',
        tratamiento_referencia: 'Nitrofurantoína por 7 días y aumento de líquidos.',
        nombre_cargo_atiende: 'Dra. Carla Medina',
      },
      {
        fecha: '2026-06-28',
        hora: '10:00',
        motivo_consulta: 'Lumbalgia mecánica',
        historia_enfermedad_actual: 'Dolor lumbar post esfuerzo.',
        revision_por_sistemas: 'Sin síntomas urinarios.',
        examen_fisico: 'Dolor a palpación lumbar sin puño percusión positiva.',
        impresion_clinica: 'Lumbalgia del embarazo.',
        tratamiento_referencia: 'Paracetamol SOS y ejercicios posturales.',
        nombre_cargo_atiende: 'Lic. Ana López',
      },
    ],
    puerperio: [
      {
        numero_atencion: 1,
        fecha: '2026-11-01',
        hora: '08:00',
        signos_peligro: 'Ninguno',
        dias_despues_parto: 2,
        lugar_atencion_parto: 'CAP El Chal',
        quien_atendio_parto: 'Dra. Carla Medina',
        recien_nacido_vivo: true,
        tipo_parto: 'vaginal',
        tuvo_apego_inmediato: true,
        lactancia_materna_exclusiva: true,
        herida_operatoria: 'No aplica',
        pa_sistolica: 112,
        pa_diastolica: 72,
        frecuencia_cardiaca: 78,
        frecuencia_respiratoria: 18,
        temperatura: 36.8,
        examen_mamas: 'Mamas blandas, buena bajada de leche.',
        examen_ginecologico: 'Loquios normales, sin desgarros complicados.',
        orientacion_consejeria: 'Lactancia y signos de alarma.',
        impresion_clinica: 'Puerperio fisiológico.',
        tratamiento: 'Seguimiento domiciliario.',
        nombre_cargo_atiende: 'Lic. Ana López',
      },
      {
        numero_atencion: 2,
        fecha: '2026-11-12',
        hora: '09:30',
        signos_peligro: 'Ninguno',
        dias_despues_parto: 13,
        lugar_atencion_parto: 'CAP El Chal',
        quien_atendio_parto: 'Dra. Carla Medina',
        recien_nacido_vivo: true,
        tipo_parto: 'vaginal',
        tuvo_apego_inmediato: true,
        lactancia_materna_exclusiva: true,
        herida_operatoria: 'No aplica',
        pa_sistolica: 110,
        pa_diastolica: 70,
        frecuencia_cardiaca: 76,
        frecuencia_respiratoria: 18,
        temperatura: 36.5,
        examen_mamas: 'Adecuado vaciamiento.',
        examen_ginecologico: 'Involución uterina adecuada.',
        orientacion_consejeria: 'Planificación familiar y autocuidado.',
        impresion_clinica: 'Puerperio normal tardío.',
        tratamiento: 'Alta del control puerperal.',
        nombre_cargo_atiende: 'Lic. Ana López',
      },
    ],
    planParto: {
      fecha: '2026-06-21',
      nombre_conyuge: 'Luis Alberto Tun',
      telefono: '55112233',
      fecha_nacimiento: '1998-08-14',
      estado_civil: 'Unida',
      pueblo: 'Maya',
      escolaridad: 'Diversificado',
      con_quien_vive: 'Conyuge e hijo',
      idioma: 'Qeqchi y español',
      ha_tenido_atencion_prenatal: true,
      no_embarazos: 3,
      no_partos: 1,
      no_abortos: 1,
      no_hijos_vivos: 1,
      no_hijos_muertos: 0,
      fur: '2026-01-18',
      fecha_probable_parto: '2026-10-25',
      no_cesareas: 0,
      fecha_ultima_cesarea: null,
      edad_gestacional_semanas: 22,
      parto_anterior_hospital: false,
      parto_anterior_caimi: true,
      parto_anterior_comadrona: false,
      parto_anterior_clinica_privada: false,
      parto_anterior_otro: '',
      peligro_dolor_cabeza: true,
      peligro_vision_borrosa: true,
      peligro_embarazo_multiple: false,
      peligro_hemorragia_vaginal: true,
      peligro_edema_mi: true,
      peligro_nino_transverso: false,
      peligro_dolor_estomago: true,
      peligro_salida_liquidos: true,
      peligro_convulsiones: true,
      peligro_fiebre: true,
      peligro_ausencia_mov_fetales: true,
      peligro_placenta_no_salia: false,
      posicion_parto: 'Semi-reclinada',
      lugar_atencion_parto: 'CAP',
      horas_distancia: 1,
      kms_servicio: 6.5,
      casa_materna_cercana: true,
      usara_casa_materna: false,
      como_trasladara: 'Vehículo familiar',
      quien_acompanara: 'Luis Alberto Tun',
      bebida_durante_parto: 'Incaparina',
      bebida_despues_parto: 'Atol de maíz',
      ropa_nino: true,
      ropa_madre: true,
      otros_articulos: 'Pañales, toallas sanitarias y documentos.',
      lleva_dpi_madre: true,
      lleva_dpi_conyuge: true,
      lleva_partida_nacimiento: false,
      cuenta_ahorro: true,
      comunicado_comite: true,
      con_quien_hijos: 'Abuela materna',
      quien_cuida_casa: 'Hermana',
      telefono_vehiculo: '58114455',
      responsable_activar: 'Esposo',
      nombre_activara_plan: 'Luis Alberto Tun',
      nombre_proveedor_salud: 'Dra. Carla Medina',
      no_registro: 'PP-001-DEMO',
      servicio_salud: 'CAP El Chal',
      lugar_residencia: 'El Chal Centro',
      edad_gestacional_au: 22,
      acompana_traslado: 'Esposo',
      acompana_parto: 'Esposo',
    },
    riesgo: {
      fecha: '2026-05-03',
      telefono: '55112233',
      pueblo: 'maya',
      migrante: false,
      estado_civil: 'unida',
      escolaridad: 'Diversificado',
      ocupacion: 'Comerciante',
      nombre_esposo_conviviente: 'Luis Alberto Tun',
      edad_esposo: 31,
      pueblo_esposo: 'maya',
      escolaridad_esposo: 'Básico',
      ocupacion_esposo: 'Agricultor',
      distancia_servicio_km: 6.5,
      tiempo_horas: 0.5,
      fecha_ultima_regla: '2026-01-18',
      fecha_probable_parto: '2026-10-25',
      no_embarazos: 3,
      no_partos: 1,
      no_cesareas: 0,
      no_abortos: 1,
      no_hijos_vivos: 1,
      no_hijos_muertos: 0,
      edad_embarazo_semanas: 15,
      muerte_fetal_neonatal_previa: false,
      abortos_espontaneos_3mas: false,
      gestas_3mas: true,
      peso_ultimo_bebe_menor_2500g: false,
      peso_ultimo_bebe_mayor_4500g: false,
      antec_hipertension_preeclampsia: false,
      cirugias_tracto_reproductivo: false,
      embarazo_multiple: false,
      menor_20_anos: false,
      mayor_35_anos: false,
      paciente_rh_negativo: false,
      hemorragia_vaginal: false,
      vih_positivo_sifilis: false,
      presion_diastolica_90mas: false,
      anemia: false,
      desnutricion_obesidad: false,
      dolor_abdominal: false,
      sintomatologia_urinaria: true,
      ictericia: false,
      diabetes: false,
      enfermedad_renal: false,
      enfermedad_corazon: false,
      hipertension_arterial: false,
      consumo_drogas_alcohol_tabaco: false,
      otra_enfermedad_severa: false,
      otra_enfermedad_descripcion: '',
      referida_a: 'CAP El Chal - seguimiento interno',
      nombre_personal_atendio: 'Dra. Carla Medina',
    },
    referencias: [
      {
        fecha: '2026-05-30',
        lugar_referencia: 'Laboratorio distrital',
        diagnostico: 'Control de uroanálisis por IVU.',
      },
    ],
  },
  {
    paciente: {
      no_expediente: 'DEMO-EMB-002',
      cui: '4012456780202',
      nombre_establecimiento: 'CAP El Chal',
      distrito: 'Distrito Sur Oriente',
      area_salud: 'Peten, Area Sur Oriente',
      categoria_servicio: 'CAP',
      nombres: 'Yasmin Alejandra',
      apellidos: 'Pop Caal',
      fecha_nacimiento: '2007-11-02',
      rango_edad: '14_19',
      clasificacion_alfa_beta: 'BETA',
      domicilio: 'Aldea Nuevo Horizonte, casa 7',
      municipio: 'Dolores',
      territorio: 'Territorio 3',
      sector: 'Sector C',
      comunidad: 'Nuevo Horizonte',
      telefono: '56997788',
      cobertura_igss: false,
      cobertura_privada: false,
      cobertura_privada_detalle: null,
      viene_referida: false,
      referida_de: null,
      nivel_estudios: 'basico',
      ultimo_anio_aprobado: 2,
      profesion_oficio: 'Estudiante',
      estado_civil: 'soltera',
      vive_sola: false,
      nombre_esposo_conviviente: 'Carlos Estuardo Caal',
      es_migrante: true,
      migrante_municipio_depto_pais: 'Poptun, Peten',
      pueblo: 'mestizo',
      comunidad_linguistica: 'Español',
      fuma_activamente: false,
      fuma_pasivamente: true,
      consume_drogas: false,
      consume_alcohol: false,
      fuma_activamente_1er_trimestre: false,
      fuma_activamente_2do_trimestre: false,
      fuma_activamente_3er_trimestre: false,
      fuma_pasivamente_1er_trimestre: true,
      fuma_pasivamente_2do_trimestre: false,
      fuma_pasivamente_3er_trimestre: false,
      consume_alcohol_1er_trimestre: false,
      consume_alcohol_2do_trimestre: false,
      consume_alcohol_3er_trimestre: false,
      consume_drogas_1er_trimestre: false,
      consume_drogas_2do_trimestre: false,
      consume_drogas_3er_trimestre: false,
      violencia_1er_trimestre: false,
      violencia_2do_trimestre: false,
      violencia_3er_trimestre: false,
      embarazo_abuso_sexual: false,
      fur: '2026-02-02',
      fpp: '2026-11-09',
      eg_confiable_fur: true,
      eg_confiable_usg: false,
      gestas_previas: 0,
      abortos: 0,
      partos_vaginales: 0,
      cesareas: 0,
      nacidos_vivos: 0,
      nacidos_muertos: 0,
      hijos_viven: 0,
      muertos_antes_1sem: 0,
      muertos_despues_1sem: 0,
      cirugia_genito_urinaria: false,
      infertilidad: false,
      fin_embarazo_anterior: null,
      fin_embarazo_menos_1anio: false,
      embarazo_planeado: false,
      fracaso_metodo: 'barrera',
      antec_diabetes: false,
      antec_diabetes_tipo: null,
      antec_tbc: false,
      antec_hipertension: false,
      antec_preeclampsia: false,
      antec_eclampsia: false,
      antec_cardiopatia: false,
      antec_nefropatia: false,
      antec_otra_condicion: true,
      antec_otra_condicion_desc: 'Anemia leve previa al embarazo',
      cirugia_genito_urinaria_pers: false,
      fam_diabetes: false,
      fam_tbc: false,
      fam_hipertension: false,
      fam_preeclampsia: false,
      fam_eclampsia: false,
      fam_cardiopatia: false,
      fam_gemelos: true,
      fam_otra_condicion_medica_grave: false,
      rn_nc: false,
      rn_normal: false,
      rn_menor_2500g: false,
      rn_mayor_4000g: false,
      antec_vih_positivo: false,
      antec_emb_ectopico_num: 0,
      antec_emb_ectopico: false,
      antec_gemelares: false,
      abortos_3_espont_consecutivos: false,
      antec_violencia: false,
      tiene_ficha_riesgo: true,
    },
    embarazo: {
      numero_embarazo: 1,
      estado: 'activo',
      fur: '2026-02-02',
      fpp: '2026-11-09',
      fecha_inicio: '2026-02-02',
      fecha_cierre: null,
      observaciones: 'Paciente demo adolescente, expediente completo con riesgo obstétrico.',
    },
    vacunas: [
      { tipo_vacuna: 'td_tdap', momento: 'durante_embarazo', numero_dosis: 1, fecha_dosis: '2026-05-08' },
      { tipo_vacuna: 'td_tdap', momento: 'durante_embarazo', numero_dosis: 2, fecha_dosis: '2026-06-08' },
      { tipo_vacuna: 'influenza', momento: 'durante_embarazo', numero_dosis: 1, fecha_dosis: '2026-05-08' },
    ],
    controles: [
      {
        numero_control: 1,
        fecha: '2026-05-08',
        hora: '07:50',
        motivo_consulta: 'Primer control prenatal por embarazo adolescente.',
        peligro_hemorragia_vaginal: false,
        peligro_palidez: true,
        peligro_dolor_cabeza: true,
        peligro_hipertension: false,
        peligro_dolor_epigastrico: false,
        peligro_trastornos_visuales: false,
        peligro_fiebre: false,
        peligro_otro: 'Mareo ocasional',
        edad_gestacional_semanas: 13,
        nombre_acompanante: 'Madre',
        nombre_cargo_atiende: 'Dra. Carla Medina',
        pa_sistolica: 100,
        pa_diastolica: 60,
        frecuencia_cardiaca: 92,
        frecuencia_respiratoria: 20,
        temperatura: 36.7,
        perimetro_braquial_cm: 23.4,
        peso_kg: 47.3,
        talla_cm: 152.0,
        imc: 20.47,
        examen_bucodental: false,
        examen_mamas: true,
        altura_uterina_cm: 13.0,
        fcf: 152,
        movimientos_fetales: false,
        situacion_fetal: 'Longitudinal',
        presentacion_fetal: 'No aplica',
        sangre_manchado: false,
        verrugas_herpes_papilomas: false,
        flujo_vaginal: true,
        otros_ginecologico: 'Flujo leve sin mal olor.',
        hematologia_realizada: true,
        hematologia_resultado: 'Hb 10.4 g/dL',
        glicemia_realizada: true,
        glicemia_resultado: '82 mg/dL',
        grupo_rh_realizado: true,
        grupo_rh_resultado: 'A-',
        orina_realizada: true,
        orina_bacteriuria: false,
        orina_proteinuria: false,
        heces_realizada: true,
        heces_resultado: 'Normal',
        vih_realizado: true,
        vih_resultado: 'negativo',
        vih_resultado_valor: 'No reactivo',
        vdrl_realizado: true,
        vdrl_resultado: 'negativo',
        vdrl_tratamiento_indicado: false,
        torch_realizado: false,
        torch_resultado_positivo: false,
        torch_resultado_valor: '',
        papanicolau_ivaa_realizado: false,
        papanicolau_ivaa_fecha_toma: null,
        papanicolau_ivaa_resultado: '',
        hepatitis_b_realizado: true,
        hepatitis_b_resultado: 'Negativo',
        otros_lab: 'Se solicita ferritina.',
        usg_realizado: true,
        usg_hallazgos: 'Gestación única de 13 semanas.',
        sulfato_ferroso: true,
        sulfato_ferroso_tabletas: 60,
        acido_folico: true,
        acido_folico_tabletas: 60,
        suplementacion_hallazgos: 'Indicada dosis reforzada por anemia.',
        suplementacion_tratamiento: 'Sulfato ferroso 2 tabs/día.',
        orient_plan_emergencia_parto: true,
        orient_alimentacion_embarazo: true,
        orient_senales_peligro: true,
        orient_lactancia_materna: true,
        orient_planificacion_familiar: false,
        orient_importancia_postparto: false,
        orient_vacunacion_nino: true,
        orient_pre_post_prueba_vih: true,
        orient_importancia_atenciones: true,
        orient_tratamiento_its_pareja: false,
        orient_otros: 'Consejería para adolescente y apoyo familiar.',
        impresion_clinica: 'Embarazo adolescente con anemia leve y Rh negativo.',
        tratamiento: 'Sulfato ferroso, ácido fólico, control estrecho.',
        cita_siguiente: '2026-05-29',
      },
      {
        numero_control: 2,
        fecha: '2026-05-29',
        hora: '08:20',
        motivo_consulta: 'Seguimiento de anemia.',
        peligro_hemorragia_vaginal: false,
        peligro_palidez: true,
        peligro_dolor_cabeza: false,
        peligro_hipertension: false,
        peligro_dolor_epigastrico: false,
        peligro_trastornos_visuales: false,
        peligro_fiebre: false,
        peligro_otro: '',
        edad_gestacional_semanas: 16,
        nombre_acompanante: 'Madre',
        nombre_cargo_atiende: 'Lic. Ana López',
        pa_sistolica: 102,
        pa_diastolica: 64,
        frecuencia_cardiaca: 88,
        frecuencia_respiratoria: 19,
        temperatura: 36.5,
        perimetro_braquial_cm: 23.7,
        peso_kg: 48.0,
        talla_cm: 152.0,
        imc: 20.78,
        examen_bucodental: false,
        examen_mamas: true,
        altura_uterina_cm: 16.0,
        fcf: 150,
        movimientos_fetales: true,
        situacion_fetal: 'Longitudinal',
        presentacion_fetal: 'No aplica',
        sangre_manchado: false,
        verrugas_herpes_papilomas: false,
        flujo_vaginal: false,
        otros_ginecologico: '',
        hematologia_realizada: true,
        hematologia_resultado: 'Hb 10.8 g/dL',
        glicemia_realizada: false,
        glicemia_resultado: '',
        grupo_rh_realizado: false,
        grupo_rh_resultado: '',
        orina_realizada: true,
        orina_bacteriuria: false,
        orina_proteinuria: false,
        heces_realizada: false,
        heces_resultado: '',
        vih_realizado: false,
        vih_resultado: '',
        vih_resultado_valor: '',
        vdrl_realizado: false,
        vdrl_resultado: '',
        vdrl_tratamiento_indicado: false,
        torch_realizado: false,
        torch_resultado_positivo: false,
        torch_resultado_valor: '',
        papanicolau_ivaa_realizado: false,
        papanicolau_ivaa_fecha_toma: null,
        papanicolau_ivaa_resultado: '',
        hepatitis_b_realizado: false,
        hepatitis_b_resultado: '',
        otros_lab: '',
        usg_realizado: false,
        usg_hallazgos: '',
        sulfato_ferroso: true,
        sulfato_ferroso_tabletas: 60,
        acido_folico: true,
        acido_folico_tabletas: 60,
        suplementacion_hallazgos: 'Mejor tolerancia.',
        suplementacion_tratamiento: 'Continuar tratamiento.',
        orient_plan_emergencia_parto: true,
        orient_alimentacion_embarazo: true,
        orient_senales_peligro: true,
        orient_lactancia_materna: true,
        orient_planificacion_familiar: true,
        orient_importancia_postparto: true,
        orient_vacunacion_nino: true,
        orient_pre_post_prueba_vih: false,
        orient_importancia_atenciones: true,
        orient_tratamiento_its_pareja: false,
        orient_otros: 'Adherencia al hierro.',
        impresion_clinica: 'Mejora parcial de anemia.',
        tratamiento: 'Continuar sulfato ferroso.',
        cita_siguiente: '2026-06-26',
      },
      {
        numero_control: 3,
        fecha: '2026-06-26',
        hora: '08:15',
        motivo_consulta: 'Control prenatal con revisión de ultrasonido.',
        peligro_hemorragia_vaginal: false,
        peligro_palidez: false,
        peligro_dolor_cabeza: false,
        peligro_hipertension: false,
        peligro_dolor_epigastrico: false,
        peligro_trastornos_visuales: false,
        peligro_fiebre: false,
        peligro_otro: '',
        edad_gestacional_semanas: 20,
        nombre_acompanante: 'Madre',
        nombre_cargo_atiende: 'Dra. Carla Medina',
        pa_sistolica: 104,
        pa_diastolica: 66,
        frecuencia_cardiaca: 86,
        frecuencia_respiratoria: 19,
        temperatura: 36.6,
        perimetro_braquial_cm: 24.0,
        peso_kg: 49.1,
        talla_cm: 152.0,
        imc: 21.25,
        examen_bucodental: true,
        examen_mamas: true,
        altura_uterina_cm: 20.0,
        fcf: 148,
        movimientos_fetales: true,
        situacion_fetal: 'Longitudinal',
        presentacion_fetal: 'Cefálica',
        sangre_manchado: false,
        verrugas_herpes_papilomas: false,
        flujo_vaginal: false,
        otros_ginecologico: '',
        hematologia_realizada: true,
        hematologia_resultado: 'Hb 11.2 g/dL',
        glicemia_realizada: true,
        glicemia_resultado: '85 mg/dL',
        grupo_rh_realizado: false,
        grupo_rh_resultado: '',
        orina_realizada: true,
        orina_bacteriuria: false,
        orina_proteinuria: false,
        heces_realizada: false,
        heces_resultado: '',
        vih_realizado: false,
        vih_resultado: '',
        vih_resultado_valor: '',
        vdrl_realizado: false,
        vdrl_resultado: '',
        vdrl_tratamiento_indicado: false,
        torch_realizado: false,
        torch_resultado_positivo: false,
        torch_resultado_valor: '',
        papanicolau_ivaa_realizado: false,
        papanicolau_ivaa_fecha_toma: null,
        papanicolau_ivaa_resultado: '',
        hepatitis_b_realizado: false,
        hepatitis_b_resultado: '',
        otros_lab: '',
        usg_realizado: true,
        usg_hallazgos: 'Crecimiento fetal adecuado, placenta fúndica.',
        sulfato_ferroso: true,
        sulfato_ferroso_tabletas: 60,
        acido_folico: true,
        acido_folico_tabletas: 30,
        suplementacion_hallazgos: 'Anemia resuelta.',
        suplementacion_tratamiento: 'Mantener dosis de sostén.',
        orient_plan_emergencia_parto: true,
        orient_alimentacion_embarazo: true,
        orient_senales_peligro: true,
        orient_lactancia_materna: true,
        orient_planificacion_familiar: true,
        orient_importancia_postparto: true,
        orient_vacunacion_nino: true,
        orient_pre_post_prueba_vih: false,
        orient_importancia_atenciones: true,
        orient_tratamiento_its_pareja: false,
        orient_otros: 'Continuar red de apoyo.',
        impresion_clinica: 'Evolución favorable con riesgo controlado.',
        tratamiento: 'Continuar control frecuente.',
        cita_siguiente: '2026-07-24',
      },
      {
        numero_control: 4,
        fecha: '2026-07-24',
        hora: '09:05',
        motivo_consulta: 'Control de seguimiento de embarazo de alto riesgo social.',
        peligro_hemorragia_vaginal: false,
        peligro_palidez: false,
        peligro_dolor_cabeza: false,
        peligro_hipertension: false,
        peligro_dolor_epigastrico: false,
        peligro_trastornos_visuales: false,
        peligro_fiebre: false,
        peligro_otro: '',
        edad_gestacional_semanas: 24,
        nombre_acompanante: 'Madre',
        nombre_cargo_atiende: 'Dra. Carla Medina',
        pa_sistolica: 106,
        pa_diastolica: 68,
        frecuencia_cardiaca: 84,
        frecuencia_respiratoria: 18,
        temperatura: 36.5,
        perimetro_braquial_cm: 24.3,
        peso_kg: 50.0,
        talla_cm: 152.0,
        imc: 21.64,
        examen_bucodental: true,
        examen_mamas: true,
        altura_uterina_cm: 24.0,
        fcf: 146,
        movimientos_fetales: true,
        situacion_fetal: 'Longitudinal',
        presentacion_fetal: 'Cefálica',
        sangre_manchado: false,
        verrugas_herpes_papilomas: false,
        flujo_vaginal: false,
        otros_ginecologico: '',
        hematologia_realizada: false,
        hematologia_resultado: '',
        glicemia_realizada: false,
        glicemia_resultado: '',
        grupo_rh_realizado: false,
        grupo_rh_resultado: '',
        orina_realizada: true,
        orina_bacteriuria: false,
        orina_proteinuria: false,
        heces_realizada: false,
        heces_resultado: '',
        vih_realizado: false,
        vih_resultado: '',
        vih_resultado_valor: '',
        vdrl_realizado: false,
        vdrl_resultado: '',
        vdrl_tratamiento_indicado: false,
        torch_realizado: false,
        torch_resultado_positivo: false,
        torch_resultado_valor: '',
        papanicolau_ivaa_realizado: false,
        papanicolau_ivaa_fecha_toma: null,
        papanicolau_ivaa_resultado: '',
        hepatitis_b_realizado: false,
        hepatitis_b_resultado: '',
        otros_lab: '',
        usg_realizado: false,
        usg_hallazgos: '',
        sulfato_ferroso: true,
        sulfato_ferroso_tabletas: 30,
        acido_folico: true,
        acido_folico_tabletas: 30,
        suplementacion_hallazgos: 'Sin eventos adversos.',
        suplementacion_tratamiento: 'Continuar suplementos.',
        orient_plan_emergencia_parto: true,
        orient_alimentacion_embarazo: true,
        orient_senales_peligro: true,
        orient_lactancia_materna: true,
        orient_planificacion_familiar: true,
        orient_importancia_postparto: true,
        orient_vacunacion_nino: true,
        orient_pre_post_prueba_vih: false,
        orient_importancia_atenciones: true,
        orient_tratamiento_its_pareja: false,
        orient_otros: 'Se refuerza apoyo psicosocial.',
        impresion_clinica: 'Riesgo obstétrico compensado.',
        tratamiento: 'Continuar vigilancia y referencia si signos de alarma.',
        cita_siguiente: '2026-08-21',
      },
    ],
    morbilidad: [
      {
        fecha: '2026-05-18',
        hora: '10:15',
        motivo_consulta: 'Náuseas y vómitos',
        historia_enfermedad_actual: 'Náuseas matutinas persistentes.',
        revision_por_sistemas: 'Sin datos de deshidratación.',
        examen_fisico: 'Mucosas húmedas, sin compromiso hemodinámico.',
        impresion_clinica: 'Hiperemesis leve del embarazo.',
        tratamiento_referencia: 'Metoclopramida PRN y dieta fraccionada.',
        nombre_cargo_atiende: 'Lic. Ana López',
      },
      {
        fecha: '2026-06-10',
        hora: '12:10',
        motivo_consulta: 'Cefalea ocasional',
        historia_enfermedad_actual: 'Cefalea tensional vespertina.',
        revision_por_sistemas: 'Sin fosfenos ni epigastralgia.',
        examen_fisico: 'PA normal, hidratación adecuada.',
        impresion_clinica: 'Cefalea tensional.',
        tratamiento_referencia: 'Paracetamol y educación sobre hidratación.',
        nombre_cargo_atiende: 'Dra. Carla Medina',
      },
    ],
    puerperio: [
      {
        numero_atencion: 1,
        fecha: '2026-11-15',
        hora: '08:40',
        signos_peligro: 'Ninguno',
        dias_despues_parto: 3,
        lugar_atencion_parto: 'Hospital de Dolores',
        quien_atendio_parto: 'Dr. René Solís',
        recien_nacido_vivo: true,
        tipo_parto: 'cesarea',
        tuvo_apego_inmediato: true,
        lactancia_materna_exclusiva: true,
        herida_operatoria: 'Herida limpia y seca.',
        pa_sistolica: 108,
        pa_diastolica: 70,
        frecuencia_cardiaca: 82,
        frecuencia_respiratoria: 18,
        temperatura: 36.8,
        examen_mamas: 'Pezones íntegros.',
        examen_ginecologico: 'Loquios escasos, involución adecuada.',
        orientacion_consejeria: 'Cuidados de herida y lactancia.',
        impresion_clinica: 'Puerperio post cesárea normal.',
        tratamiento: 'Curación diaria.',
        nombre_cargo_atiende: 'Lic. Ana López',
      },
      {
        numero_atencion: 2,
        fecha: '2026-11-26',
        hora: '09:10',
        signos_peligro: 'Ninguno',
        dias_despues_parto: 14,
        lugar_atencion_parto: 'Hospital de Dolores',
        quien_atendio_parto: 'Dr. René Solís',
        recien_nacido_vivo: true,
        tipo_parto: 'cesarea',
        tuvo_apego_inmediato: true,
        lactancia_materna_exclusiva: true,
        herida_operatoria: 'Retiro de puntos sin complicación.',
        pa_sistolica: 106,
        pa_diastolica: 68,
        frecuencia_cardiaca: 78,
        frecuencia_respiratoria: 18,
        temperatura: 36.5,
        examen_mamas: 'Sin mastitis.',
        examen_ginecologico: 'Sin datos de infección.',
        orientacion_consejeria: 'PF post evento obstétrico.',
        impresion_clinica: 'Puerperio satisfactorio.',
        tratamiento: 'Alta de control.',
        nombre_cargo_atiende: 'Dra. Carla Medina',
      },
    ],
    planParto: {
      fecha: '2026-06-26',
      nombre_conyuge: 'Carlos Estuardo Caal',
      telefono: '56997788',
      fecha_nacimiento: '2007-11-02',
      estado_civil: 'Soltera',
      pueblo: 'Mestiza',
      escolaridad: 'Básico',
      con_quien_vive: 'Madre y pareja',
      idioma: 'Español',
      ha_tenido_atencion_prenatal: true,
      no_embarazos: 1,
      no_partos: 0,
      no_abortos: 0,
      no_hijos_vivos: 0,
      no_hijos_muertos: 0,
      fur: '2026-02-02',
      fecha_probable_parto: '2026-11-09',
      no_cesareas: 0,
      fecha_ultima_cesarea: null,
      edad_gestacional_semanas: 20,
      parto_anterior_hospital: false,
      parto_anterior_caimi: false,
      parto_anterior_comadrona: false,
      parto_anterior_clinica_privada: false,
      parto_anterior_otro: '',
      peligro_dolor_cabeza: true,
      peligro_vision_borrosa: true,
      peligro_embarazo_multiple: false,
      peligro_hemorragia_vaginal: true,
      peligro_edema_mi: true,
      peligro_nino_transverso: false,
      peligro_dolor_estomago: true,
      peligro_salida_liquidos: true,
      peligro_convulsiones: true,
      peligro_fiebre: true,
      peligro_ausencia_mov_fetales: true,
      peligro_placenta_no_salia: false,
      posicion_parto: 'De lado',
      lugar_atencion_parto: 'Hospital',
      horas_distancia: 1,
      kms_servicio: 18.0,
      casa_materna_cercana: true,
      usara_casa_materna: true,
      como_trasladara: 'Ambulancia',
      quien_acompanara: 'Madre',
      bebida_durante_parto: 'Suero oral',
      bebida_despues_parto: 'Avena',
      ropa_nino: true,
      ropa_madre: true,
      otros_articulos: 'Pañalera, documentos y ropa adicional.',
      lleva_dpi_madre: true,
      lleva_dpi_conyuge: false,
      lleva_partida_nacimiento: true,
      cuenta_ahorro: false,
      comunicado_comite: true,
      con_quien_hijos: 'No aplica',
      quien_cuida_casa: 'Madre',
      telefono_vehiculo: '42113344',
      responsable_activar: 'Madre',
      nombre_activara_plan: 'Rosalina Pop',
      nombre_proveedor_salud: 'Dra. Carla Medina',
      no_registro: 'PP-002-DEMO',
      servicio_salud: 'CAP El Chal',
      lugar_residencia: 'Nuevo Horizonte, Dolores',
      edad_gestacional_au: 20,
      acompana_traslado: 'Madre',
      acompana_parto: 'Madre',
    },
    riesgo: {
      fecha: '2026-05-08',
      telefono: '56997788',
      pueblo: 'mestizo',
      migrante: true,
      estado_civil: 'soltera',
      escolaridad: 'Básico',
      ocupacion: 'Estudiante',
      nombre_esposo_conviviente: 'Carlos Estuardo Caal',
      edad_esposo: 20,
      pueblo_esposo: 'mestizo',
      escolaridad_esposo: 'Básico',
      ocupacion_esposo: 'Moto mensajero',
      distancia_servicio_km: 18.0,
      tiempo_horas: 1.0,
      fecha_ultima_regla: '2026-02-02',
      fecha_probable_parto: '2026-11-09',
      no_embarazos: 1,
      no_partos: 0,
      no_cesareas: 0,
      no_abortos: 0,
      no_hijos_vivos: 0,
      no_hijos_muertos: 0,
      edad_embarazo_semanas: 13,
      muerte_fetal_neonatal_previa: false,
      abortos_espontaneos_3mas: false,
      gestas_3mas: false,
      peso_ultimo_bebe_menor_2500g: false,
      peso_ultimo_bebe_mayor_4500g: false,
      antec_hipertension_preeclampsia: false,
      cirugias_tracto_reproductivo: false,
      embarazo_multiple: false,
      menor_20_anos: true,
      mayor_35_anos: false,
      paciente_rh_negativo: true,
      hemorragia_vaginal: false,
      vih_positivo_sifilis: false,
      presion_diastolica_90mas: false,
      anemia: true,
      desnutricion_obesidad: false,
      dolor_abdominal: false,
      sintomatologia_urinaria: false,
      ictericia: false,
      diabetes: false,
      enfermedad_renal: false,
      enfermedad_corazon: false,
      hipertension_arterial: false,
      consumo_drogas_alcohol_tabaco: false,
      otra_enfermedad_severa: false,
      otra_enfermedad_descripcion: '',
      referida_a: 'Hospital de Dolores',
      nombre_personal_atendio: 'Dra. Carla Medina',
    },
    referencias: [
      {
        fecha: '2026-05-09',
        lugar_referencia: 'Hospital de Dolores',
        diagnostico: 'Valoración por Rh negativo y control especializado.',
      },
    ],
  },
];

async function seedDemoPatients() {
  const client = await pool.connect();

  try {
    await client.query('BEGIN');

    const { rows: userRows } = await client.query(
      `SELECT id
       FROM usuarios
       ORDER BY CASE WHEN username = 'admin' THEN 0 ELSE 1 END, id
       LIMIT 1`
    );

    if (!userRows[0]) {
      throw new Error('No existe ningun usuario para registrar los pacientes demo.');
    }

    const userId = userRows[0].id;
    const results = [];

    for (const demoPatient of demoPatients) {
      try {
        results.push(await recreateDemoPatient(client, demoPatient, userId));
      } catch (error) {
        error.message = `Paciente ${demoPatient.paciente.no_expediente}: ${error.message}`;
        throw error;
      }
    }

    await client.query('COMMIT');

    console.log('Demo pacientes cargados correctamente:');
    for (const item of results) {
      console.log(`- paciente_id=${item.pacienteId}, embarazo_id=${item.embarazoId}`);
    }
  } catch (error) {
    await client.query('ROLLBACK');
    console.error('Error cargando pacientes demo:', error.message);
    process.exitCode = 1;
  } finally {
    client.release();
    await pool.end();
  }
}

seedDemoPatients();
