function patientField(id, label, aliases, help, expected, operationalNote) {
  return { id: `paciente_${id}`, label, aliases, section: 'expediente', tabs: [],
    forms: ['nueva_paciente', 'editar_paciente'], help, expected, operationalNote };
}

function riskField(id, label, aliases, help, expected, operationalNote) {
  return { id: `riesgo_${id}`, label, aliases, section: 'ficha_riesgo', tabs: [],
    forms: ['ficha_riesgo'], help, expected, operationalNote };
}

function vaccineField(id, label, aliases, help, expected, operationalNote) {
  return { id: `vacuna_${id}`, label, aliases, section: 'vacunas', tabs: [],
    forms: ['nueva_vacuna', 'editar_vacuna'], help, expected, operationalNote };
}

function puerperiumField(id, label, aliases, help, expected, operationalNote) {
  return { id: `puerperio_${id}`, label, aliases, section: 'puerperio', tabs: [],
    forms: ['nuevo_puerperio', 'editar_puerperio'], help, expected, operationalNote };
}

function morbidityField(id, label, aliases, help, expected, operationalNote) {
  return { id: `morbilidad_${id}`, label, aliases, section: 'morbilidad', tabs: [],
    forms: ['nueva_morbilidad', 'editar_morbilidad'], help, expected, operationalNote };
}

function birthPlanField(id, label, aliases, help, expected, operationalNote) {
  return { id: `plan_parto_${id}`, label, aliases, section: 'plan_parto', tabs: [],
    forms: ['plan_parto'], help, expected, operationalNote };
}

const chatbotFieldHelp = Object.freeze([
  {
    id: 'numero_control', label: 'No. Control', aliases: ['numero de control', 'número de control'],
    section: 'control_prenatal', tabs: ['general'],
    help: 'Identifica el número de esta atención en la secuencia de controles prenatales.',
    expected: 'Selecciona un número en la lista No. Control.',
    operationalNote: 'Está en la pestaña General de Nuevo o Editar control.',
  },
  {
    id: 'cita_siguiente', label: 'Cita siguiente', aliases: ['proxima cita', 'próxima cita', 'siguiente cita'],
    section: 'control_prenatal', tabs: ['general'],
    help: 'Registra la fecha de la siguiente cita asociada al control.',
    expected: 'Es una fecha en el selector del formulario.',
    operationalNote: 'Está en General. Si la cita ya está programada, el campo se muestra de solo lectura y se reprograma desde el calendario.',
  },
  {
    id: 'acompanante', label: 'Nombre del acompañante', aliases: ['acompanante', 'acompañante'],
    section: 'control_prenatal', tabs: ['general'],
    help: 'Identifica a la persona acompañante de esta atención.',
    expected: 'Es un campo de texto para el nombre del acompañante.',
    operationalNote: 'Está en la pestaña General.',
  },
  {
    id: 'semanas_gestacion', label: 'Semanas de gestación', aliases: ['semanas de gestacion', 'edad gestacional'],
    section: 'control_prenatal', tabs: ['general'],
    help: 'Muestra las semanas de gestación calculadas para la fecha del control.',
    expected: 'Es un número calculado por el sistema a partir de FUR y fecha del control; el campo es de solo lectura.',
    operationalNote: 'Está en la pestaña General.',
  },
  {
    id: 'hematologia', label: 'Hematología', aliases: ['hematologia'],
    section: 'control_prenatal', tabs: ['laboratorio'],
    help: 'Agrupa el estado de realización y el resultado registrado para Hematología.',
    expected: 'Marca Realizado cuando corresponda; entonces se habilita un campo de texto para el resultado disponible.',
    operationalNote: 'Está en Laboratorio. El formulario no identifica este resultado como hemoglobina ni los equipara.',
  },
  {
    id: 'vih', label: 'VIH', aliases: ['prueba de vih'],
    section: 'control_prenatal', tabs: ['laboratorio'],
    help: 'Agrupa el estado de realización y el resultado registrado para VIH.',
    expected: 'Marca Realizado cuando corresponda; el resultado se elige entre las opciones que muestra el formulario.',
    operationalNote: 'Está en Laboratorio. Al editar un control, su captura requiere el permiso controles.ver_vih.',
  },
  patientField('no_expediente', 'No. de Expediente', ['numero de expediente', 'número de expediente', 'expediente'],
    'Identifica el expediente de la paciente dentro del sistema.', 'Es texto de hasta 30 caracteres.',
    'Está en Establecimiento y es obligatorio al crear la paciente.'),
  patientField('cui', 'CUI', ['dpi'], 'Es el código único de identificación de la paciente.',
    'Es opcional; si se registra, debe contener exactamente 13 dígitos.', 'Está en Establecimiento.'),
  patientField('nombres', 'Nombres', ['nombre de paciente'], 'Registra los nombres de la paciente.',
    'Es texto obligatorio de hasta 150 caracteres al crear el registro.', 'Está en Paciente.'),
  patientField('apellidos', 'Apellidos', ['apellido de paciente'], 'Registra los apellidos de la paciente.',
    'Es texto obligatorio de hasta 150 caracteres al crear el registro.', 'Está en Paciente.'),
  patientField('fecha_nacimiento', 'Fecha de nacimiento', ['nacimiento'],
    'Registra la fecha de nacimiento; el sistema calcula la edad a partir de ella.',
    'Selecciona una fecha. Si no se conoce, el formulario ofrece el campo Edad para registrarla manualmente.', 'Está en Paciente.'),
  patientField('comunidad', 'Comunidad', ['comunidad de residencia'],
    'Registra la comunidad de residencia.', 'En El Chal puede seleccionarse del catálogo; fuera de El Chal se admite texto libre.',
    'Está en Paciente. La selección del catálogo completa territorio y sector.'),
  patientField('telefono', 'Teléfono', ['telefono de paciente'], 'Registra un teléfono de contacto.',
    'Es texto opcional de hasta 20 caracteres.', 'Está en Paciente.'),
  patientField('pueblo', 'Pueblo', ['pueblo etnia', 'etnia'], 'Registra el pueblo indicado en el formulario.',
    'Selecciona una opción: Maya, Garífuna, Xinka, Ladino/Mestizo u Otro.', 'Está en Paciente.'),
  patientField('estado_civil', 'Estado civil', ['estado civil'], 'Registra el estado civil.',
    'Selecciona una opción de la lista visible.', 'Está en Paciente.'),
  patientField('nivel_estudios', 'Nivel de Estudios', ['escolaridad', 'nivel de estudios'],
    'Registra el nivel de estudios.', 'Selecciona una opción de la lista visible.', 'Está en Paciente.'),
  patientField('profesion_oficio', 'Profesión u oficio', ['ocupacion', 'ocupación'],
    'Registra la profesión u oficio.', 'Es texto opcional de hasta 100 caracteres.', 'Está en Paciente.'),
  patientField('fur', 'FUR', ['ultima regla', 'última menstruación', 'fecha de última regla'],
    'FUR significa Fecha de Última Regla.', 'Es una fecha que se selecciona en el formulario.',
    'Está en Gestación. Al cambiar FUR, el sistema propone una FPP calculada.'),
  patientField('fpp', 'FPP', ['fecha probable de parto'],
    'FPP significa Fecha Probable de Parto.', 'Es una fecha; el formulario la calcula inicialmente desde FUR y permite editarla.',
    'Está en Gestación. La explicación del campo no sustituye la intención separada de calcular FPP.'),
  patientField('gestas_previas', 'Gestas previas', ['gestas', 'embarazos anteriores'],
    'Registra el número de gestas previas.', 'Es un número entero entre 0 y 25.', 'Está en Gestación → Antecedentes obstétricos.'),
  patientField('partos', 'Partos', ['numero de partos'], 'Registra el número de partos en antecedentes obstétricos.',
    'Es un número entero entre 0 y 25.', 'Está en Gestación → Antecedentes obstétricos.'),
  patientField('abortos', 'Abortos', ['numero de abortos'], 'Registra el número de abortos en antecedentes obstétricos.',
    'Es un número entero entre 0 y 25.', 'Está en Gestación → Antecedentes obstétricos.'),
  patientField('cesareas', 'Cesáreas', ['numero de cesareas'], 'Registra el número de cesáreas en antecedentes obstétricos.',
    'Es un número entero entre 0 y 15.', 'Está en Gestación → Antecedentes obstétricos.'),
  patientField('hijos_viven', 'Hijos que viven', ['hijos vivos'], 'Registra el número de hijos que viven.',
    'Es un número entero entre 0 y 25.', 'Está en Gestación → Antecedentes obstétricos.'),
  riskField('fecha', 'Fecha', ['fecha de evaluacion', 'fecha de evaluación'],
    'Fecha de evaluación de la ficha de riesgo.', 'Selecciona una fecha; el formulario la requiere.', 'Está en Información general.'),
  riskField('telefono', 'Teléfono', ['telefono de riesgo'], 'Teléfono de contacto registrado en la ficha.',
    'Es texto opcional de hasta 20 caracteres.', 'Está en Información general.'),
  riskField('pueblo', 'Pueblo', ['pueblo en ficha'], 'Pueblo registrado en la ficha.',
    'Es texto opcional de hasta 30 caracteres.', 'Está en Información general.'),
  riskField('estado_civil', 'Estado civil', ['estado civil en ficha'], 'Estado civil registrado en la ficha.',
    'Es texto opcional de hasta 30 caracteres.', 'Está en Información general.'),
  riskField('escolaridad', 'Escolaridad', ['escolaridad en ficha'], 'Escolaridad registrada en la ficha.',
    'Es texto opcional de hasta 50 caracteres.', 'Está en Información general.'),
  riskField('ocupacion', 'Ocupación', ['ocupacion en ficha'], 'Ocupación registrada en la ficha.',
    'Es texto opcional de hasta 100 caracteres.', 'Está en Información general.'),
  riskField('fecha_ultima_regla', 'FUR', ['ultima regla', 'última menstruación', 'fecha de última regla'],
    'FUR significa Fecha de Última Regla.', 'Es una fecha editable, precargada cuando el embarazo tiene FUR.',
    'Está en Información general de la Ficha de riesgo.'),
  riskField('fecha_probable_parto', 'FPP', ['fecha probable de parto'],
    'FPP significa Fecha Probable de Parto.', 'Es una fecha editable, precargada cuando el embarazo tiene FPP.',
    'Está en Información general de la Ficha de riesgo.'),
  riskField('tiempo_horas', 'Tiempo al servicio', ['tiempo horas', 'tiempo al servicio'],
    'Registra el tiempo de traslado al servicio.', 'Es un número de horas entre 0 y 72; admite decimales.',
    'Está en Información general. El formulario muestra ejemplos de conversión de minutos a horas.'),
  riskField('referida_a', 'Referida a', ['destino de referencia'],
    'Registra el destino de referencia consignado en la ficha.', 'Es texto de hasta 255 caracteres.',
    'Está en Referencia y seguimiento; si hay características de riesgo marcadas, el formulario solicita confirmar la referencia.'),
  riskField('nombre_personal_atendio', 'Nombre del personal que atendió', ['personal que atiende', 'personal atiende'],
    'Identifica al personal que atendió la evaluación.', 'Es texto de hasta 150 caracteres.',
    'Está en Referencia y seguimiento.'),
  riskField('no_embarazos', 'No. de embarazos', ['numero de embarazos'],
    'Registra el número de embarazos en los antecedentes de la ficha.', 'Es un número entero entre 0 y 25.',
    'Está en Condiciones de riesgo evaluadas; Lía no determina si un factor debe marcarse.'),
  riskField('distancia_servicio_km', 'Distancia al servicio', ['distancia al servicio'],
    'Registra la distancia al servicio de salud.', 'Es un número de kilómetros entre 0 y 500; admite decimales.',
    'Está en Información general.'),
  vaccineField('tipo_vacuna', 'Tipo de vacuna', ['vacuna', 'tipo de vacuna'],
    'Identifica la vacuna que se documenta.', 'El selector ofrece TD, Tdap, Influenza y SR/SPR.',
    'TD muestra 3 dosis y 2 refuerzos; Tdap una aplicación por embarazo; Influenza se registra como aplicación simple por temporada; SR/SPR muestra 2 dosis. El sistema verifica las reglas al guardar.'),
  vaccineField('numero_dosis', 'Posición de dosis', ['posicion dosis', 'posición/dosis', 'numero de dosis', 'número de dosis'],
    'Ubica la aplicación dentro del esquema de la vacuna seleccionada.',
    'TD ofrece Dosis 1, 2 y 3 y Refuerzos 1 y 2; Tdap una posición; SR/SPR Dosis 1 y 2.',
    'No aparece para Influenza, que usa el valor interno 1. Las posiciones ya registradas pueden estar deshabilitadas; verifica el carné o antecedente.'),
  vaccineField('momento', 'Momento de aplicación', ['momento', 'momento de vacuna'],
    'Indica cuándo ocurrió la aplicación respecto del embarazo.',
    'Selecciona Previo al embarazo, Durante el embarazo o Postparto/aborto, según el antecedente documentado.',
    'Está en Documenta la aplicación; el sistema compara el momento con las fechas disponibles.'),
  vaccineField('fecha_dosis', 'Fecha de aplicación', ['fecha de vacuna', 'fecha dosis'],
    'Registra la fecha clínica de la aplicación.', 'Selecciona una fecha sin hora; es obligatoria y no puede ser futura.',
    'Está en Documenta la aplicación. Los registros de embarazo cerrado permanecen en solo lectura.'),
  puerperiumField('numero_atencion', 'No. atención', ['numero de atencion', 'número de atención'],
    'Identifica si se documenta la primera o segunda atención de puerperio.', 'Es un número entero: 1 o 2.',
    'Está en Parto y resultado. La segunda atención puede heredar datos del parto de la primera.'),
  puerperiumField('fecha', 'Fecha', ['fecha de puerperio'],
    'Fecha de la atención de puerperio.', 'Selecciona una fecha; es obligatoria.',
    'Está en Parto y resultado. En una segunda atención nueva, cambiarla recalcula los días después del parto.'),
  puerperiumField('dias_despues_parto', 'Días después del parto', ['dias despues del parto', 'dias postparto'],
    'Registra los días transcurridos después del parto.', 'Es un número entero entre 0 y 60.',
    'Está en Parto y resultado. En la segunda atención nueva puede calcularse desde la fecha y la primera atención.'),
  puerperiumField('lugar_atencion_parto', 'Lugar del parto', ['lugar de atencion del parto'],
    'Consigna el lugar del parto documentado.', 'Es un campo de texto.',
    'Está en Parto y resultado; en la segunda atención nueva puede heredarse de la primera.'),
  puerperiumField('quien_atendio_parto', 'Quién atendió parto', ['quien atendio el parto', 'personal del parto'],
    'Identifica a quien atendió el parto.', 'Es un campo de texto.',
    'Está en Parto y resultado; en la segunda atención nueva puede heredarse de la primera.'),
  puerperiumField('tipo_parto', 'Tipo de parto', ['tipo de parto'],
    'Registra el tipo de parto documentado.', 'Selecciona Vaginal o Cesárea.',
    'Está en Parto y resultado; en la segunda atención nueva puede heredarse de la primera.'),
  puerperiumField('recien_nacido_vivo', 'Recién nacido vivo', ['rn vivo', 'recien nacido vivo'],
    'Registra la casilla de recién nacido vivo según el dato documentado.', 'Es una casilla de sí/no.',
    'Está en Parto y resultado; Lía no determina su valor.'),
  puerperiumField('tuvo_apego_inmediato', 'Apego inmediato', ['apego inmediato'],
    'Registra la casilla de apego inmediato.', 'Es una casilla de sí/no.',
    'Está en Parto y resultado de la primera atención; no se muestra en la segunda.'),
  puerperiumField('lactancia_materna_exclusiva', 'Lactancia materna exclusiva', ['lactancia exclusiva'],
    'Registra la casilla de lactancia materna exclusiva.', 'Es una casilla de sí/no.',
    'Está en Puerperio inmediato; Lía no determina su valor.'),
  puerperiumField('nombre_cargo_atiende', 'Nombre/cargo atiende', ['personal que atiende', 'nombre y cargo de quien atiende'],
    'Identifica al personal responsable de esta atención de puerperio.', 'Es un campo de texto.',
    'Está en Seguimiento y observaciones.'),
  morbidityField('fecha', 'Fecha de morbilidad', ['fecha de la nota'],
    'Fecha de la atención documentada.', 'Selecciona una fecha; inicia con la fecha actual y puede editarse.', 'Está en Identidad del evento.'),
  morbidityField('hora', 'Hora de morbilidad', ['hora de la nota'],
    'Hora de la atención documentada.', 'Selecciona una hora; inicia con la hora actual y puede editarse.', 'Está en Identidad del evento.'),
  morbidityField('motivo_consulta', 'Motivo de consulta', ['motivo'],
    'Documenta el motivo por el que se registra esta atención.', 'Es un campo de texto.', 'Está en Identidad del evento.'),
  morbidityField('historia_enfermedad_actual', 'Historia enfermedad actual', ['historia actual', 'historia de enfermedad actual'],
    'Documenta la historia de la enfermedad actual según la atención realizada.', 'Es un área de texto libre.', 'Está en Evaluación; Lía no interpreta la historia.'),
  morbidityField('revision_por_sistemas', 'Revisión por sistemas', ['revision de sistemas'],
    'Documenta la revisión por sistemas realizada.', 'Es un área de texto libre.', 'Está en Evaluación; Lía no interpreta hallazgos.'),
  morbidityField('examen_fisico', 'Examen físico', ['examen fisico'],
    'Documenta los hallazgos del examen físico realizado.', 'Es un área de texto libre.', 'Está en Evaluación; Lía no interpreta hallazgos.'),
  morbidityField('impresion_clinica', 'Impresión clínica', ['impresion clinica'],
    'Documenta la impresión clínica formulada por el personal responsable.', 'Es un área de texto libre.', 'Está en Evaluación; Lía no formula diagnósticos.'),
  morbidityField('tratamiento_referencia', 'Tratamiento / Referencia', ['tratamiento', 'referencia'],
    'Documenta el tratamiento indicado o la referencia realizada por el personal responsable.', 'Es un área de texto libre.',
    'Está en Conducta; Lía no indica tratamientos, medicamentos ni decisiones de referencia.'),
  morbidityField('nombre_cargo_atiende', 'Nombre / cargo atiende', ['personal que atiende en morbilidad', 'responsable de la nota'],
    'Identifica a quien atendió y su cargo en esta nota de morbilidad.', 'Es un solo campo de texto para nombre y cargo.', 'Está en Identidad del evento.'),
  birthPlanField('no_registro', 'CUI (No. de registro)', ['no de registro en plan', 'cui en plan de parto'],
    'Identifica el número de registro usado en el plan.', 'Es texto editable; se precarga con el CUI de la paciente cuando existe.', 'Está en Información general.'),
  birthPlanField('servicio_salud', 'Servicio de salud', ['establecimiento en plan'],
    'Identifica el servicio de salud del plan.', 'Es texto editable; se precarga desde el expediente o con CAP El Chal.', 'Está en Información general.'),
  birthPlanField('lugar_residencia', 'Lugar de residencia', ['residencia en plan'],
    'Registra la residencia de la paciente para este plan.', 'Es texto editable; se precarga desde comunidad o domicilio si constan en el expediente.', 'Está en Información general.'),
  birthPlanField('nombre_conyuge', 'Nombre cónyuge / conviviente', ['conyuge en plan', 'conviviente en plan'],
    'Identifica a la persona consignada como cónyuge o conviviente.', 'Es texto editable; puede precargarse desde la ficha de riesgo o el expediente.', 'Está en Información general.'),
  birthPlanField('telefono', 'Teléfono del plan', ['telefono en plan de parto'],
    'Registra un teléfono de contacto del plan.', 'Es texto editable; puede precargarse desde la ficha de riesgo o la paciente.', 'Está en Información general.'),
  birthPlanField('fecha_nacimiento', 'Fecha de nacimiento en plan', ['nacimiento en plan'],
    'Registra la fecha de nacimiento usada en el plan.', 'Es una fecha editable; puede precargarse desde la paciente.', 'Está en Información general.'),
  birthPlanField('con_quien_vive', 'Con quién vive', ['convivencia en plan'],
    'Registra con quién vive la paciente.', 'Selecciona Esposo, Sola, Familia o Amigo/a; el formulario puede proponer una opción desde el expediente.', 'Está en Información general.'),
  birthPlanField('no_embarazos', 'No. embarazos en plan', ['embarazos en plan'],
    'Registra el número de embarazos para el plan.', 'Es un número editable; puede precargarse desde la ficha de riesgo o los antecedentes de la paciente.', 'Está en Antecedentes del embarazo.'),
  birthPlanField('fur', 'FUR en plan de parto', ['ultima regla en plan'],
    'FUR significa Fecha de Última Regla.', 'Es una fecha editable que puede precargarse desde la ficha de riesgo o el embarazo.', 'Está en Antecedentes del embarazo.'),
  birthPlanField('fecha_probable_parto', 'FPP en plan de parto', ['fecha probable de parto en plan'],
    'FPP significa Fecha Probable de Parto.', 'Es una fecha editable que puede precargarse desde la ficha de riesgo o el embarazo; este formulario no la recalcula al cambiar FUR.', 'Está en Antecedentes del embarazo.'),
  birthPlanField('edad_gestacional_semanas', 'Edad gestacional por UR', ['edad gestacional ur'],
    'Muestra las semanas de gestación calculadas para la fecha del plan.', 'Es de solo lectura; el sistema la calcula a partir de FUR y fecha del plan.', 'Está en Antecedentes del embarazo.'),
  birthPlanField('edad_gestacional_au', 'Edad gestacional por AU', ['edad gestacional au'],
    'Registra el dato de edad gestacional por AU usado en el plan.', 'Es un número editable; puede precargarse desde el último control prenatal.', 'Está en Antecedentes del embarazo.'),
  birthPlanField('peligro_hemorragia_vaginal', 'Hemorragia vaginal en signos de peligro', ['hemorragia en plan'],
    'Registra si el signo aparece marcado entre los reconocidos en el plan.', 'Es un control de sí/no; puede venir marcado por datos previos.', 'Está en Signos de peligro reconocidos; Lía no determina si aplica.'),
  birthPlanField('posicion_parto', 'Posición para la atención del parto', ['posicion para parto'],
    'Registra la posición prevista para la atención del parto.', 'Selecciona una opción visible: semi-reclinada, acostada, cuclillas, rodillas, de pie u Otro.', 'Está en Preferencias para la atención.'),
  birthPlanField('posicion_parto_otro', 'Especifique otra posición', ['otra posicion de parto'],
    'Detalla la posición cuando se selecciona Otro.', 'Es texto editable y solo aparece al elegir Otro.', 'Está en Preferencias para la atención.'),
  birthPlanField('lugar_atencion_parto', 'Lugar de atención del parto', ['lugar previsto para el parto', 'donde sera el parto'],
    'Registra el lugar previsto para la atención del parto.', 'Selecciona CAP, CAIMI, Hospital, Clínica privada u Otro.', 'Está en Preferencias para la atención.'),
  birthPlanField('lugar_atencion_parto_otro', 'Especifique otro lugar', ['otro lugar de parto'],
    'Detalla el lugar cuando se selecciona Otro.', 'Es texto editable y solo aparece al elegir Otro.', 'Está en Preferencias para la atención.'),
  birthPlanField('horas_distancia', 'Horas de distancia', ['tiempo de traslado en plan'],
    'Registra el tiempo de traslado al servicio previsto.', 'Es un número de horas entre 0 y 72; admite fracciones como 1.5 y puede precargarse desde la ficha de riesgo.', 'Está en Ruta y transporte.'),
  birthPlanField('kms_servicio', 'Kilómetros al servicio', ['distancia al servicio en plan'],
    'Registra la distancia al servicio.', 'Es un número editable que puede precargarse desde la ficha de riesgo.', 'Está en Ruta y transporte.'),
  birthPlanField('como_trasladara', 'Cómo se trasladará', ['transporte', 'medio de traslado'],
    'Registra el medio de transporte previsto.', 'Selecciona Vehículo familiar, Ambulancia, Bomberos u Otro.', 'Está en Ruta y transporte.'),
  birthPlanField('usara_casa_materna', 'Usará casa materna', ['casa materna'],
    'Registra la opción indicada en el plan sobre uso de casa materna.', 'Es un control de sí/no.', 'Está en Apoyos y artículos preparados; Lía no decide esta opción.'),
  birthPlanField('ropa_nino', 'Ropa para niño', ['ropa del bebe'],
    'Registra si se preparó ropa para el niño.', 'Es un control de sí/no.', 'Está en Apoyos y artículos preparados.'),
  birthPlanField('lleva_dpi_madre', 'Lleva DPI de la madre', ['dpi de la madre en plan'],
    'Registra si se consigna el documento de la madre entre los artículos preparados.', 'Es un control de sí/no; puede venir marcado si la paciente tiene CUI.', 'Está en Apoyos y artículos preparados.'),
  birthPlanField('otros_articulos', 'Otros artículos', ['articulos adicionales'],
    'Registra otros artículos preparados.', 'Es texto editable.', 'Está en Apoyos y artículos preparados.'),
  birthPlanField('acompana_traslado', 'Quién acompañará el traslado', ['persona que acompaña el traslado'],
    'Registra la persona prevista para acompañar el traslado.', 'Selecciona Cónyuge, Hermano/a, Madre/Padre, Suegra o Vecina.', 'Está en Acompañamiento y cuidados.'),
  birthPlanField('acompana_parto', 'Quién acompañará durante el parto', ['acompanante del parto', 'persona que acompaña'],
    'Registra la persona prevista para acompañar durante el parto.', 'Selecciona Esposo, Comadrona o Familiar.', 'Está en Acompañamiento y cuidados.'),
  birthPlanField('con_quien_hijos', 'Con quién quedarán los hijos', ['cuidado de los hijos'],
    'Registra con quién quedarán los hijos.', 'Selecciona Hijos mayores, Parientes, Vecinos u Otros.', 'Está en Acompañamiento y cuidados.'),
  birthPlanField('quien_cuida_casa', 'Quién cuidará la casa', ['cuidado de la casa'],
    'Registra quién cuidará la casa.', 'Selecciona Parientes, Vecinos u Otros.', 'Está en Acompañamiento y cuidados.'),
  birthPlanField('telefono_vehiculo', 'Teléfono del vehículo', ['contacto del vehiculo'],
    'Registra el teléfono de contacto del vehículo previsto.', 'Es texto editable.', 'Está en Acompañamiento y cuidados.'),
  birthPlanField('responsable_activar', 'Responsable de activar', ['responsable de activar plan'],
    'Registra quién activará el plan.', 'Selecciona una de las personas ofrecidas en el formulario.', 'Está en Responsables del plan.'),
  birthPlanField('nombre_activara_plan', 'Nombre quien activará el plan', ['nombre del responsable del plan'],
    'Identifica a la persona que activará el plan.', 'Es texto editable; puede completarse con el nombre del cónyuge cuando este sea el responsable seleccionado.', 'Está en Responsables del plan.'),
  birthPlanField('nombre_proveedor_salud', 'Nombre proveedor de salud', ['proveedor de salud en plan'],
    'Identifica al proveedor de salud consignado en el plan.', 'Es texto editable; puede precargarse desde el último control o la ficha de riesgo.', 'Está en Responsables del plan.'),
]);

const CHATBOT_FIELD_IDS = Object.freeze(chatbotFieldHelp.map(({ id }) => id));

module.exports = { chatbotFieldHelp, CHATBOT_FIELD_IDS };
