function patientField(id, label, aliases, help, expected, operationalNote) {
  return { id: `paciente_${id}`, label, aliases, section: 'expediente', tabs: [],
    forms: ['nueva_paciente', 'editar_paciente'], help, expected, operationalNote };
}

function riskField(id, label, aliases, help, expected, operationalNote) {
  return { id: `riesgo_${id}`, label, aliases, section: 'ficha_riesgo', tabs: [],
    forms: ['ficha_riesgo'], help, expected, operationalNote };
}

function vaccineField(id, label, aliases, help, expected, operationalNote) {
  return { id: `vacuna_${id}`, label, aliases, section: 'vacunas', tabs: [],
    forms: ['nueva_vacuna', 'editar_vacuna'], help, expected, operationalNote };
}

function puerperiumField(id, label, aliases, help, expected, operationalNote) {
  return { id: `puerperio_${id}`, label, aliases, section: 'puerperio', tabs: [],
    forms: ['nuevo_puerperio', 'editar_puerperio'], help, expected, operationalNote };
}

const chatbotFieldHelp = Object.freeze([
  {
    id: 'numero_control', label: 'No. Control', aliases: ['numero de control', 'número de control'],
    section: 'control_prenatal', tabs: ['general'],
    help: 'Identifica el número de esta atención en la secuencia de controles prenatales.',
    expected: 'Selecciona un número en la lista No. Control.',
    operationalNote: 'Está en la pestaña General de Nuevo o Editar control.',
  },
  {
    id: 'cita_siguiente', label: 'Cita siguiente', aliases: ['proxima cita', 'próxima cita', 'siguiente cita'],
    section: 'control_prenatal', tabs: ['general'],
    help: 'Registra la fecha de la siguiente cita asociada al control.',
    expected: 'Es una fecha en el selector del formulario.',
    operationalNote: 'Está en General. Si la cita ya está programada, el campo se muestra de solo lectura y se reprograma desde el calendario.',
  },
  {
    id: 'acompanante', label: 'Nombre del acompañante', aliases: ['acompanante', 'acompañante'],
    section: 'control_prenatal', tabs: ['general'],
    help: 'Identifica a la persona acompañante de esta atención.',
    expected: 'Es un campo de texto para el nombre del acompañante.',
    operationalNote: 'Está en la pestaña General.',
  },
  {
    id: 'semanas_gestacion', label: 'Semanas de gestación', aliases: ['semanas de gestacion', 'edad gestacional'],
    section: 'control_prenatal', tabs: ['general'],
    help: 'Muestra las semanas de gestación calculadas para la fecha del control.',
    expected: 'Es un número calculado por el sistema a partir de FUR y fecha del control; el campo es de solo lectura.',
    operationalNote: 'Está en la pestaña General.',
  },
  {
    id: 'hematologia', label: 'Hematología', aliases: ['hematologia'],
    section: 'control_prenatal', tabs: ['laboratorio'],
    help: 'Agrupa el estado de realización y el resultado registrado para Hematología.',
    expected: 'Marca Realizado cuando corresponda; entonces se habilita un campo de texto para el resultado disponible.',
    operationalNote: 'Está en Laboratorio. El formulario no identifica este resultado como hemoglobina ni los equipara.',
  },
  {
    id: 'vih', label: 'VIH', aliases: ['prueba de vih'],
    section: 'control_prenatal', tabs: ['laboratorio'],
    help: 'Agrupa el estado de realización y el resultado registrado para VIH.',
    expected: 'Marca Realizado cuando corresponda; el resultado se elige entre las opciones que muestra el formulario.',
    operationalNote: 'Está en Laboratorio. Al editar un control, su captura requiere el permiso controles.ver_vih.',
  },
  patientField('no_expediente', 'No. de Expediente', ['numero de expediente', 'número de expediente', 'expediente'],
    'Identifica el expediente de la paciente dentro del sistema.', 'Es texto de hasta 30 caracteres.',
    'Está en Establecimiento y es obligatorio al crear la paciente.'),
  patientField('cui', 'CUI', ['dpi'], 'Es el código único de identificación de la paciente.',
    'Es opcional; si se registra, debe contener exactamente 13 dígitos.', 'Está en Establecimiento.'),
  patientField('nombres', 'Nombres', ['nombre de paciente'], 'Registra los nombres de la paciente.',
    'Es texto obligatorio de hasta 150 caracteres al crear el registro.', 'Está en Paciente.'),
  patientField('apellidos', 'Apellidos', ['apellido de paciente'], 'Registra los apellidos de la paciente.',
    'Es texto obligatorio de hasta 150 caracteres al crear el registro.', 'Está en Paciente.'),
  patientField('fecha_nacimiento', 'Fecha de nacimiento', ['nacimiento'],
    'Registra la fecha de nacimiento; el sistema calcula la edad a partir de ella.',
    'Selecciona una fecha. Si no se conoce, el formulario ofrece el campo Edad para registrarla manualmente.', 'Está en Paciente.'),
  patientField('comunidad', 'Comunidad', ['comunidad de residencia'],
    'Registra la comunidad de residencia.', 'En El Chal puede seleccionarse del catálogo; fuera de El Chal se admite texto libre.',
    'Está en Paciente. La selección del catálogo completa territorio y sector.'),
  patientField('telefono', 'Teléfono', ['telefono de paciente'], 'Registra un teléfono de contacto.',
    'Es texto opcional de hasta 20 caracteres.', 'Está en Paciente.'),
  patientField('pueblo', 'Pueblo', ['pueblo etnia', 'etnia'], 'Registra el pueblo indicado en el formulario.',
    'Selecciona una opción: Maya, Garífuna, Xinka, Ladino/Mestizo u Otro.', 'Está en Paciente.'),
  patientField('estado_civil', 'Estado civil', ['estado civil'], 'Registra el estado civil.',
    'Selecciona una opción de la lista visible.', 'Está en Paciente.'),
  patientField('nivel_estudios', 'Nivel de Estudios', ['escolaridad', 'nivel de estudios'],
    'Registra el nivel de estudios.', 'Selecciona una opción de la lista visible.', 'Está en Paciente.'),
  patientField('profesion_oficio', 'Profesión u oficio', ['ocupacion', 'ocupación'],
    'Registra la profesión u oficio.', 'Es texto opcional de hasta 100 caracteres.', 'Está en Paciente.'),
  patientField('fur', 'FUR', ['ultima regla', 'última menstruación', 'fecha de última regla'],
    'FUR significa Fecha de Última Regla.', 'Es una fecha que se selecciona en el formulario.',
    'Está en Gestación. Al cambiar FUR, el sistema propone una FPP calculada.'),
  patientField('fpp', 'FPP', ['fecha probable de parto'],
    'FPP significa Fecha Probable de Parto.', 'Es una fecha; el formulario la calcula inicialmente desde FUR y permite editarla.',
    'Está en Gestación. La explicación del campo no sustituye la intención separada de calcular FPP.'),
  patientField('gestas_previas', 'Gestas previas', ['gestas', 'embarazos anteriores'],
    'Registra el número de gestas previas.', 'Es un número entero entre 0 y 25.', 'Está en Gestación → Antecedentes obstétricos.'),
  patientField('partos', 'Partos', ['numero de partos'], 'Registra el número de partos en antecedentes obstétricos.',
    'Es un número entero entre 0 y 25.', 'Está en Gestación → Antecedentes obstétricos.'),
  patientField('abortos', 'Abortos', ['numero de abortos'], 'Registra el número de abortos en antecedentes obstétricos.',
    'Es un número entero entre 0 y 25.', 'Está en Gestación → Antecedentes obstétricos.'),
  patientField('cesareas', 'Cesáreas', ['numero de cesareas'], 'Registra el número de cesáreas en antecedentes obstétricos.',
    'Es un número entero entre 0 y 15.', 'Está en Gestación → Antecedentes obstétricos.'),
  patientField('hijos_viven', 'Hijos que viven', ['hijos vivos'], 'Registra el número de hijos que viven.',
    'Es un número entero entre 0 y 25.', 'Está en Gestación → Antecedentes obstétricos.'),
  riskField('fecha', 'Fecha', ['fecha de evaluacion', 'fecha de evaluación'],
    'Fecha de evaluación de la ficha de riesgo.', 'Selecciona una fecha; el formulario la requiere.', 'Está en Información general.'),
  riskField('telefono', 'Teléfono', ['telefono de riesgo'], 'Teléfono de contacto registrado en la ficha.',
    'Es texto opcional de hasta 20 caracteres.', 'Está en Información general.'),
  riskField('pueblo', 'Pueblo', ['pueblo en ficha'], 'Pueblo registrado en la ficha.',
    'Es texto opcional de hasta 30 caracteres.', 'Está en Información general.'),
  riskField('estado_civil', 'Estado civil', ['estado civil en ficha'], 'Estado civil registrado en la ficha.',
    'Es texto opcional de hasta 30 caracteres.', 'Está en Información general.'),
  riskField('escolaridad', 'Escolaridad', ['escolaridad en ficha'], 'Escolaridad registrada en la ficha.',
    'Es texto opcional de hasta 50 caracteres.', 'Está en Información general.'),
  riskField('ocupacion', 'Ocupación', ['ocupacion en ficha'], 'Ocupación registrada en la ficha.',
    'Es texto opcional de hasta 100 caracteres.', 'Está en Información general.'),
  riskField('fecha_ultima_regla', 'FUR', ['ultima regla', 'última menstruación', 'fecha de última regla'],
    'FUR significa Fecha de Última Regla.', 'Es una fecha editable, precargada cuando el embarazo tiene FUR.',
    'Está en Información general de la Ficha de riesgo.'),
  riskField('fecha_probable_parto', 'FPP', ['fecha probable de parto'],
    'FPP significa Fecha Probable de Parto.', 'Es una fecha editable, precargada cuando el embarazo tiene FPP.',
    'Está en Información general de la Ficha de riesgo.'),
  riskField('tiempo_horas', 'Tiempo al servicio', ['tiempo horas', 'tiempo al servicio'],
    'Registra el tiempo de traslado al servicio.', 'Es un número de horas entre 0 y 72; admite decimales.',
    'Está en Información general. El formulario muestra ejemplos de conversión de minutos a horas.'),
  riskField('referida_a', 'Referida a', ['destino de referencia'],
    'Registra el destino de referencia consignado en la ficha.', 'Es texto de hasta 255 caracteres.',
    'Está en Referencia y seguimiento; si hay características de riesgo marcadas, el formulario solicita confirmar la referencia.'),
  riskField('nombre_personal_atendio', 'Nombre del personal que atendió', ['personal que atiende', 'personal atiende'],
    'Identifica al personal que atendió la evaluación.', 'Es texto de hasta 150 caracteres.',
    'Está en Referencia y seguimiento.'),
  riskField('no_embarazos', 'No. de embarazos', ['numero de embarazos'],
    'Registra el número de embarazos en los antecedentes de la ficha.', 'Es un número entero entre 0 y 25.',
    'Está en Condiciones de riesgo evaluadas; Lía no determina si un factor debe marcarse.'),
  riskField('distancia_servicio_km', 'Distancia al servicio', ['distancia al servicio'],
    'Registra la distancia al servicio de salud.', 'Es un número de kilómetros entre 0 y 500; admite decimales.',
    'Está en Información general.'),
  vaccineField('tipo_vacuna', 'Tipo de vacuna', ['vacuna', 'tipo de vacuna'],
    'Identifica la vacuna que se documenta.', 'El selector ofrece TD, Tdap, Influenza y SR/SPR.',
    'TD muestra 3 dosis y 2 refuerzos; Tdap una aplicación por embarazo; Influenza se registra como aplicación simple por temporada; SR/SPR muestra 2 dosis. El sistema verifica las reglas al guardar.'),
  vaccineField('numero_dosis', 'Posición de dosis', ['posicion dosis', 'posición/dosis', 'numero de dosis', 'número de dosis'],
    'Ubica la aplicación dentro del esquema de la vacuna seleccionada.',
    'TD ofrece Dosis 1, 2 y 3 y Refuerzos 1 y 2; Tdap una posición; SR/SPR Dosis 1 y 2.',
    'No aparece para Influenza, que usa el valor interno 1. Las posiciones ya registradas pueden estar deshabilitadas; verifica el carné o antecedente.'),
  vaccineField('momento', 'Momento de aplicación', ['momento', 'momento de vacuna'],
    'Indica cuándo ocurrió la aplicación respecto del embarazo.',
    'Selecciona Previo al embarazo, Durante el embarazo o Postparto/aborto, según el antecedente documentado.',
    'Está en Documenta la aplicación; el sistema compara el momento con las fechas disponibles.'),
  vaccineField('fecha_dosis', 'Fecha de aplicación', ['fecha de vacuna', 'fecha dosis'],
    'Registra la fecha clínica de la aplicación.', 'Selecciona una fecha sin hora; es obligatoria y no puede ser futura.',
    'Está en Documenta la aplicación. Los registros de embarazo cerrado permanecen en solo lectura.'),
  puerperiumField('numero_atencion', 'No. atención', ['numero de atencion', 'número de atención'],
    'Identifica si se documenta la primera o segunda atención de puerperio.', 'Es un número entero: 1 o 2.',
    'Está en Parto y resultado. La segunda atención puede heredar datos del parto de la primera.'),
  puerperiumField('fecha', 'Fecha', ['fecha de puerperio'],
    'Fecha de la atención de puerperio.', 'Selecciona una fecha; es obligatoria.',
    'Está en Parto y resultado. En una segunda atención nueva, cambiarla recalcula los días después del parto.'),
  puerperiumField('dias_despues_parto', 'Días después del parto', ['dias despues del parto', 'dias postparto'],
    'Registra los días transcurridos después del parto.', 'Es un número entero entre 0 y 60.',
    'Está en Parto y resultado. En la segunda atención nueva puede calcularse desde la fecha y la primera atención.'),
  puerperiumField('lugar_atencion_parto', 'Lugar del parto', ['lugar de atencion del parto'],
    'Consigna el lugar del parto documentado.', 'Es un campo de texto.',
    'Está en Parto y resultado; en la segunda atención nueva puede heredarse de la primera.'),
  puerperiumField('quien_atendio_parto', 'Quién atendió parto', ['quien atendio el parto', 'personal del parto'],
    'Identifica a quien atendió el parto.', 'Es un campo de texto.',
    'Está en Parto y resultado; en la segunda atención nueva puede heredarse de la primera.'),
  puerperiumField('tipo_parto', 'Tipo de parto', ['tipo de parto'],
    'Registra el tipo de parto documentado.', 'Selecciona Vaginal o Cesárea.',
    'Está en Parto y resultado; en la segunda atención nueva puede heredarse de la primera.'),
  puerperiumField('recien_nacido_vivo', 'Recién nacido vivo', ['rn vivo', 'recien nacido vivo'],
    'Registra la casilla de recién nacido vivo según el dato documentado.', 'Es una casilla de sí/no.',
    'Está en Parto y resultado; Lía no determina su valor.'),
  puerperiumField('tuvo_apego_inmediato', 'Apego inmediato', ['apego inmediato'],
    'Registra la casilla de apego inmediato.', 'Es una casilla de sí/no.',
    'Está en Parto y resultado de la primera atención; no se muestra en la segunda.'),
  puerperiumField('lactancia_materna_exclusiva', 'Lactancia materna exclusiva', ['lactancia exclusiva'],
    'Registra la casilla de lactancia materna exclusiva.', 'Es una casilla de sí/no.',
    'Está en Puerperio inmediato; Lía no determina su valor.'),
  puerperiumField('nombre_cargo_atiende', 'Nombre/cargo atiende', ['personal que atiende', 'nombre y cargo de quien atiende'],
    'Identifica al personal responsable de esta atención de puerperio.', 'Es un campo de texto.',
    'Está en Seguimiento y observaciones.'),
]);

const CHATBOT_FIELD_IDS = Object.freeze(chatbotFieldHelp.map(({ id }) => id));

module.exports = { chatbotFieldHelp, CHATBOT_FIELD_IDS };
